<html><head></head><body>
<div id="sbo-rt-content"><section data-nutshell-tab="Exceptions" data-pdf-bookmark="Chapter 6. Exceptions" data-type="chapter" epub:type="chapter"><div class="chapter" id="exceptions">
<h1><span class="label">Chapter 6. </span>Exceptions</h1>
<p>Python uses<a contenteditable="false" data-primary="exceptions" data-secondary="purpose of" data-type="indexterm" id="idm44924574273968"/> <em>exceptions</em> to indicate errors and anomalies. When Python detects an error, it <em>raises</em> an exception—that is, Python signals the occurrence of an anomalous condition by passing an exception object to the exception propagation mechanism. Your code can explicitly raise an exception by executing a <span class="code"><strong>raise</strong></span> statement.</p>
<p><em>Handling<a contenteditable="false" data-primary="exception handling" data-type="indexterm" id="idm44924574270144"/></em> an exception means catching the exception object from the propagation mechanism and taking actions as needed to deal with the anomalous situation. If a program does not handle an exception, the program terminates with an error message and traceback message. However, a program can handle exceptions and keep running, despite errors or other anomalies, by using the <span class="code"><strong>try</strong></span> statement with <span class="code"><strong>except</strong></span> clauses.</p>
<p>Python also uses exceptions to indicate some situations that are not errors, and not even abnormal. For example, as covered in <a data-type="xref" href="ch03.xhtml#iterators">“Iterators”</a>, calling the <span class="code">next</span> built-in function on an iterator raises <span class="code">StopIteration</span> when the iterator has no more items. This is not an error; it is not even an anomaly, since most iterators run out of items eventually. The optimal strategies for checking and handling errors and other special situations in Python are therefore different from those in other languages; we cover them in <a data-type="xref" href="#error_checking_strategies">“Error-Checking Strategies”</a>.</p>
<p>This chapter shows how to use exceptions for errors and special situations. It also covers the <span class="code">logging</span> module of the standard library, in <a data-type="xref" href="#logging_errors">“Logging Errors”</a>, and the <span class="code"><strong>assert</strong></span> statement, in <a data-type="xref" href="#the_assert_statement">“The assert Statement”</a>.</p>
<section data-pdf-bookmark="The try Statement" data-type="sect1"><div class="sect1" id="the_try_statement">
<h1>The try Statement</h1>
<p>The<a contenteditable="false" data-primary="exceptions" data-secondary="try statement" data-type="indexterm" id="Etry06"/><a contenteditable="false" data-primary="try statement" data-type="indexterm" id="tryst06"/> <span class="code"><strong>try</strong></span> statement is Python’s core exception handling mechanism. It’s a compound statement with three kinds of optional clauses:</p>
<ol>
<li>
<p>It may have zero or more <span class="code"><strong>except</strong></span> clauses, defining how to handle particular classes of exceptions.</p>
</li>
<li>
<p>If it has <span class="code"><strong>except</strong></span> clauses, then it may also have, right afterwards, one <span class="code"><strong>else</strong></span> clause, executed only if the <span class="code"><strong>try</strong></span> suite raised no exceptions.</p>
</li>
<li>
<p>Whether or not it has <span class="code"><strong>except</strong></span> clauses, it may have a single <span class="code"><strong>finally</strong></span> clause, unconditionally executed, with the behavior covered in <a data-type="xref" href="#trysolidusexceptsolidusfinally">“try/except/finally”</a>.</p>
</li>
</ol>
<p>Python’s syntax requires the presence of at least one <span class="code"><strong>except</strong></span> clause or a <span class="code"><strong>finally</strong></span> clause, both of which might also be present in the same statement; <span class="code"><strong>else</strong></span> is only valid following one or more <span class="code"><strong>except</strong></span>s.</p>
<section data-pdf-bookmark="try/except" data-type="sect2"><div class="sect2" id="trysolidusexcept">
<h2>try/except</h2>
<p>Here’s the syntax for the <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>except</strong></span> form of the <span class="code"><strong>try</strong></span> statement:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em><code>
</code><strong><code class="k">except</code></strong><code> </code><code class="p">[</code><em><code class="n">expression</code></em><code> </code><code class="p">[</code><strong><code class="k">as</code></strong><code> </code><em><code class="n">target</code></em><code class="p">]</code><code class="p">]</code><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em><code>
</code><code class="p">[</code><strong><code class="k">else</code></strong><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em><code class="p">]</code><code>
</code><code class="p">[</code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em><code class="p">]</code></pre>
<p>This form of the <span class="code"><strong>try</strong></span> statement has one or more<a contenteditable="false" data-primary="except clause" data-type="indexterm" id="exccla06"/> <span class="code"><strong>except</strong></span> clauses, as well as an optional <span class="code"><strong>else</strong></span> clause (and an optional <span class="code"><strong>finally</strong></span> clause, whose meaning does not depend on whether <span class="code"><strong>except</strong></span> and <span class="code"><strong>else</strong></span> clauses are present: we cover this in the following section).</p>
<p>The body of each <span class="code"><strong>except</strong></span> clause is known as an<a contenteditable="false" data-primary="exception handlers" data-type="indexterm" id="idm44924574182976"/> <em>exception handler</em>. The code executes when the <span class="code"><em>expression</em></span> in the <span class="code"><strong>except</strong></span> clause matches an exception object propagating from the <span class="code"><strong>try</strong></span> clause. <span class="code"><em>expression</em></span> is a class or tuple of classes, in parentheses, and matches any instance of one of those classes or their subclasses. The optional <span class="code"><em>target</em></span> is an identifier that names a variable that Python binds to the exception object just before the exception handler executes. A handler can also obtain the current exception object by calling the <span class="code">exc_info</span> function (<span class="version">3.11+</span> or the <span class="code">exception</span> function) of the module <span class="code">sys</span> (covered in <a data-type="xref" href="ch09.xhtml#alignment_indicators">Table 9-3</a>).</p>
<p>Here is an example of the <span class="code">try/except</span> form of the <span class="code">try</span> statement:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="mi">1</code><code class="o">/</code><code class="mi">0</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">not executed</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">except</code></strong><code> </code><code class="ne">ZeroDivisionError</code><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">caught divide-by-0 attempt</code><code class="s1">'</code><code class="p">)</code></pre>
<p>When an exception is raised, execution of the <span class="code"><strong>try</strong></span> suite immediately ceases. If a <span class="code"><strong>try</strong></span> statement has several <span class="code"><strong>except</strong></span> clauses, the exception propagation mechanism checks the <span class="code"><strong>except</strong></span> clauses in order; the first <span class="code"><strong>except</strong></span> clause whose expression matches the exception object executes as the handler, and the exception propagation mechanism checks no further <span class="code"><strong>except</strong></span> clauses after that.</p>
<div data-type="note" epub:type="note">
<h1>Specific Before General</h1>
<p>Place handlers for specific cases before handlers for more general cases: when you place a general case first, the more specific <span class="code"><strong>except</strong></span> clauses that follow never execute.</p>
</div>
<p>The last <span class="code"><strong>except</strong></span> clause need not specify an expression. An <span class="code"><strong>except</strong></span> clause without any expression handles any exception that reaches it during propagation. Such unconditional handling is rare, but it does occur, often in “wrapper” functions that must perform some extra task before re-raising an exception (see <a data-type="xref" href="#the_raise_statement">“The raise Statement”</a>).</p>
<div data-type="warning" epub:type="warning">
<h1>Avoid a “Bare Except” That Doesn’t Re-Raise</h1>
<p>Beware<a contenteditable="false" data-primary="bare excepts" data-type="indexterm" id="idm44924574084480"/> of using a “bare” <span class="code"><strong>except</strong></span> (an <span class="code"><strong>except</strong></span> clause without an expression) unless you’re re-raising the exception in it: such sloppy style can make bugs very hard to find, since the bare <span class="code"><strong>except</strong></span> is overly broad and can easily mask coding errors and other kinds of bugs by allowing execution to continue after an unanticipated exception.</p>
<p>New programmers who are “just trying to get things to work” may even write code like:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><strong><code class="p">:</code></strong><code>
</code><code>    </code><em><code class="c1"># ...code that has a problem...</code></em><code>
</code><strong><code class="k">except</code></strong><strong><code class="p">:</code></strong><code>
</code><code>    </code><strong><code class="k">pass</code></strong></pre>
<p>This is a dangerous practice, since it catches important process-exiting exceptions such as <span class="code">KeyboardInterrupt</span> or <span class="code">SystemExit</span>—a loop with such an exception handler can’t be exited with Ctrl-C, and possibly not even terminated with a system<a contenteditable="false" data-primary="kill commands" data-type="indexterm" id="idm44924574063968"/> <span class="code"><strong>kill</strong></span> command. At the very least, such code should use <span class="code"><strong>except</strong></span> <span class="code">Exception:</span>, which is still overly broad but at least does not catch the process-exiting exceptions.</p>
</div>
<p>Exception propagation terminates when it finds a handler whose expression matches the exception object. When a <span class="code"><strong>try</strong></span> statement is nested (lexically in the source code, or dynamically within function calls) in the <span class="code"><strong>try</strong></span> clause of another <span class="code"><strong>try</strong></span> statement, a handler established by the inner <span class="code"><strong>try</strong></span> is reached first on propagation, so it handles the exception when it matches it. This may not be what you want. Consider this example:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="mi">1</code><code class="o">/</code><code class="mi">0</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">caught an exception</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">except</code><code> </code><code class="ne">ZeroDivisionError</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">caught divide-by-0 attempt</code><code class="s1">'</code><code class="p">)</code><code>
</code><em><code class="c1"># prints:</code></em><code class="c1"> </code><em><code class="c1">caught an exception</code></em></pre>
<p>In this case, it does not matter that the handler established by the clause <span class="code"><strong>except</strong></span> <span class="code">ZeroDivisionError</span><span class="code">:</span> in the outer <span class="code"><strong>try</strong></span> clause is more specific than the catch-all <span class="code"><strong>except</strong></span>: in the inner <span class="code"><strong>try</strong></span> clause. The outer <span class="code"><strong>try</strong></span> does not enter into the picture: the exception doesn’t propagate out of the inner <span class="code"><strong>try</strong></span>. For more on exception propagation, see <a data-type="xref" href="#exception_propagation">“Exception Propagation”</a>.</p>
<p>The optional<a contenteditable="false" data-primary="else clause" data-secondary="try-except-else" data-type="indexterm" id="idm44924573997184"/><a contenteditable="false" data-primary="control flow statements" data-secondary="else clause" data-type="indexterm" id="idm44924573973072"/> <span class="code"><strong>else</strong></span> clause of <span class="code"><strong>try</strong></span><span class="code">/<strong>except</strong></span> executes only when the <span class="code"><strong>try</strong></span> clause terminates normally. In other words, the <span class="code"><strong>else</strong></span> clause does not execute when an exception propagates from the <span class="code"><strong>try</strong></span> clause, or when the <span class="code"><strong>try</strong></span> clause exits with a<a contenteditable="false" data-primary="break keyword" data-secondary="in try/except" data-secondary-sortas="try/except" data-type="indexterm" id="idm44924573965808"/> <span class="code"><strong>break</strong></span>, <span class="code"><strong>continue</strong></span>, or <span class="code"><strong>return</strong></span> statement. Handlers established by <span class="code"><strong>try</strong>/</span><span class="code"><strong>except</strong></span> cover only the <span class="code"><strong>try</strong></span> clause, not the <span class="code"><strong>else</strong></span> clause. The <span class="code"><strong>else</strong></span> clause is useful to avoid accidentally handling unexpected exceptions. For example:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="nb">print</code><code class="p">(</code><code class="nb">repr</code><code class="p">(</code><code class="n">value</code><code class="p">)</code><code class="p">,</code><code> </code><code class="s1">'</code><code class="s1">is </code><code class="s1">'</code><code class="p">,</code><code> </code><code class="n">end</code><code class="o">=</code><code class="s1">'</code><code class="s1"> </code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="n">value</code><code> </code><code class="o">+</code><code> </code><code class="mi">0</code><code>
</code><strong><code class="k">except</code></strong><code> </code><code class="ne">TypeError</code><code class="p">:</code><code>
</code><code>    </code><em><code class="c1"># not a number, maybe a string...?</code></em><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="n">value</code><code> </code><code class="o">+</code><code> </code><code class="s1">'</code><code class="s1">'</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="ne">TypeError</code><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">neither a number nor a string</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">else</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">some kind of string</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">else</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">some kind of number</code><code class="s1">'</code><code class="p">)</code></pre>
</div></section>
<section data-pdf-bookmark="try/finally" data-type="sect2"><div class="sect2" id="trysolidusfinally">
<h2>try/finally</h2>
<p>Here’s the syntax for the <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>finally</strong></span> form of the <span class="code"><strong>try</strong></span> statement:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em><code>
</code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em></pre>
<p>This form has one<a contenteditable="false" data-primary="finally clauses" data-type="indexterm" id="idm44924573843024"/> <span class="code"><strong>finally</strong></span> clause, and no <span class="code">else</span> clause (unless it also has one or more <span class="code"><strong>except</strong></span> clauses, as covered in the following section).</p>
<p>The <span class="code"><strong>finally</strong></span> clause establishes what is known as a<a contenteditable="false" data-primary="cleanup handlers" data-type="indexterm" id="idm44924573838128"/> <em>cleanup handler</em>. This code always executes after the <span class="code"><strong>try</strong></span> clause terminates in any way. When an exception propagates from the <span class="code"><strong>try</strong></span> clause, the <span class="code"><strong>try</strong></span> clause terminates, the cleanup handler executes, and the exception keeps propagating. When no exception occurs, the cleanup handler executes anyway, regardless of whether the <span class="code"><strong>try</strong></span> clause reaches its end or exits by executing a <span class="code"><strong>break</strong></span>, <span class="code"><strong>continue</strong></span>, or <span class="code"><strong>return</strong></span> statement.</p>
<p>Cleanup handlers established with <span class="code"><strong>try</strong></span><span class="code">/<strong>finally</strong></span> offer a robust and explicit way to specify finalization code that must always execute, no matter what, to ensure consistency of program state and/or external entities (e.g., files, databases, network connections). Such assured finalization is nowadays usually best expressed via<a contenteditable="false" data-primary="context managers" data-type="indexterm" id="idm44924573806912"/> a <em>context manager</em> used in a <span class="code"><strong>with</strong></span> statement (see <a data-type="xref" href="#the_with_statement_and_context_managers">“The with Statement and Context Managers”</a>). Here is an example of the <span class="code"><strong>try</strong>/</span><span class="code"><strong>finally</strong></span> form of the <span class="code"><strong>try</strong></span> statement:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">f</code><code> </code><code class="o">=</code><code> </code><code class="nb">open</code><code class="p">(</code><code class="n">some_file</code><code class="p">,</code><code> </code><code class="s1">'</code><code class="s1">w</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="n">do_something_with_file</code><code class="p">(</code><code class="n">f</code><code class="p">)</code><code>
</code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="n">f</code><code class="o">.</code><code class="n">close</code><code class="p">(</code><code class="p">)</code></pre>
<p>and here is the corresponding, more concise and readable, example of using <span class="code"><strong>with</strong></span> for exactly the same purpose:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">with</code></strong><code> </code><code class="nb">open</code><code class="p">(</code><code class="n">some_file</code><code class="p">,</code><code> </code><code class="s1">'</code><code class="s1">w</code><code class="s1">'</code><code class="p">)</code><code> </code><strong><code class="k">as</code></strong><code> </code><code class="n">f</code><code class="p">:</code><code>
</code><code>    </code><code class="n">do_something_with_file</code><code class="p">(</code><code class="n">f</code><code class="p">)</code></pre>
<div data-type="tip">
<h1>Avoid break and return Statements in a finally Clause</h1>
<p>A <span class="code"><strong>finally</strong></span> clause may contain one or more of the statements <span class="code"><strong>continue</strong></span>, <span class="version">3.8+</span> <span class="code"><strong>break</strong></span>, or <span class="code"><strong>return</strong></span>. However, such usage may make your program less clear: exception propagation stops when such a statement executes, and most programmers would not expect propagation to be stopped within a <span class="code"><strong>finally</strong></span> clause. This usage may confuse people who are reading your code, so we recommend you avoid it.</p>
</div>
</div></section>
<section data-pdf-bookmark="try/except/finally" data-type="sect2"><div class="sect2" id="trysolidusexceptsolidusfinally">
<h2>try/except/finally</h2>
<p>A <span class="code"><strong>try</strong></span><span class="code">/<strong>except</strong>/</span><span class="code"><strong>finally</strong></span> statement, such as:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">guarded</code><code> </code><code class="n">clause</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code><code>
</code><strong><code class="k">except</code></strong><code> </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">expression</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code><code class="p">:</code><code>
</code><code>    </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">exception</code><code> </code><code class="n">handler</code><code> </code><code class="n">code</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code><code>
</code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">cleanup</code><code> </code><code class="n">code</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code></pre>
<p>is equivalent to the nested statement:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">guarded</code><code> </code><code class="n">clause</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">expression</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code><code class="p">:</code><code>
</code><code>        </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">exception</code><code> </code><code class="n">handler</code><code> </code><code class="n">code</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code><code>
</code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="o">.</code><code class="o">.</code><code class="o">.</code><em><code class="n">cleanup</code><code> </code><code class="n">code</code></em><code class="o">.</code><code class="o">.</code><code class="o">.</code></pre>
<p>A <span class="code"><strong>try</strong></span> statement can have multiple <span class="code"><strong>except</strong></span> clauses, and optionally an <span class="code"><strong>else</strong></span> clause, before a terminating <span class="code"><strong>finally</strong></span> clause. In all variations, the effect is always as just shown—that is, it’s just like nesting a <span class="code"><strong>try</strong></span><span class="code">/<strong>except</strong></span> statement, with all the <span class="code"><strong>except</strong></span> clauses and the <span class="code"><strong>else</strong></span> clause, if any, into a containing <span class="code"><strong>try</strong>/</span><span class="code"><strong>finally</strong></span> statement.<a contenteditable="false" data-primary="" data-startref="Etry06" data-type="indexterm" id="idm44924573577376"/><a contenteditable="false" data-primary="" data-startref="tryst06" data-type="indexterm" id="idm44924573546160"/><a contenteditable="false" data-primary="" data-startref="exccla06" data-type="indexterm" id="idm44924573544784"/></p>
</div></section>
</div></section>
<section data-pdf-bookmark="The raise Statement" data-type="sect1"><div class="sect1" id="the_raise_statement">
<h1>The raise Statement</h1>
<p>You<a contenteditable="false" data-primary="exceptions" data-secondary="raise statement" data-type="indexterm" id="idm44924573541568"/><a contenteditable="false" data-primary="raise statement" data-type="indexterm" id="idm44924573540160"/> can use the <span class="code"><strong>raise</strong></span> statement to raise an exception explicitly. <span class="code"><strong>raise</strong></span> is a simple statement with the following syntax:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">raise</code></strong><code> </code><code class="p">[</code><em><code class="n">expression</code></em><code> </code><code class="p">[</code><strong><code class="kn">from</code></strong><code> </code><em><code class="nn">exception</code></em><code class="p">]</code><code class="p">]</code></pre>
<p>Only an exception handler (or a function that a handler calls, directly or indirectly) can use <span class="code"><strong>raise</strong></span> without any expression. A plain <span class="code"><strong>raise</strong></span> statement re-raises the same exception object that the handler received. The handler terminates, and the exception propagation mechanism keeps going up the call stack, searching for other applicable handlers. Using <span class="code"><strong>raise</strong></span> without any expression is useful when a handler discovers that it is unable to handle an exception it receives, or can handle the exception only partially, so the exception should keep propagating to allow handlers up the call stack to perform their own handling and cleanup.</p>
<p>When <span class="code"><em>expression</em></span> is present, it must be an instance of a class inheriting from the built-in class <span class="code">BaseException</span>, and Python raises that instance.</p>
<p>When <span class="code"><strong>from</strong></span> <span class="code"><em>exception</em></span> is included (which can only occur in an <span class="code"><strong>except</strong></span> block that receives <span class="code"><em>exception</em></span>), Python raises the received expression “nested” in the newly raised exception expression. <a data-type="xref" href="#exceptions_quotation_markwrappingquotat">“Exceptions “wrapping” other exceptions or tracebacks”</a> describes this in more detail.</p>
<p>Here’s an example of a typical use of the <span class="code"><strong>raise</strong></span> statement:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">cross_product</code><code class="p">(</code><code class="n">seq1</code><code class="p">,</code><code> </code><code class="n">seq2</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">if</code><code> </code><code class="ow">not</code></strong><code> </code><code class="n">seq1</code><code> </code><strong><code class="ow">or</code><code> </code><code class="ow">not</code></strong><code> </code><code class="n">seq2</code><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">raise</code></strong><code> </code><code class="ne">ValueError</code><code class="p">(</code><code class="s1">'</code><code class="s1">Sequence arguments must be non-empty</code><code class="s1">'</code><code class="p">)</code><code> </code><a class="co" href="#c01" id="comarker1"><img alt="1" height="12" src="assets/1.png" width="12"/></a><code>
</code><code>    </code><strong><code class="k">return</code></strong><code> </code><code class="p">[</code><code class="p">(</code><code class="n">x1</code><code class="p">,</code><code> </code><code class="n">x2</code><code class="p">)</code><code> </code><strong><code class="k">for</code></strong><code> </code><code class="n">x1</code><code> </code><strong><code class="ow">in</code></strong><code> </code><code class="n">seq1</code><code> </code><strong><code class="k">for</code></strong><code> </code><code class="n">x2</code><code> </code><strong><code class="ow">in</code></strong><code> </code><code class="n">seq2</code><code class="p">]</code></pre>
<dl class="calloutlist">
<dt><a class="co" href="#comarker1" id="c01"><img alt="1" height="12" src="assets/1.png" width="12"/></a></dt>
<dd>
<p>Some people consider raising a standard exception here to be inappropriate, and would prefer to raise an instance of a custom exception, as covered later in this chapter; this book’s authors disagree with this opinion.</p>
</dd>
</dl>
<p>This <span class="code">cross_product</span> example function returns a list of all pairs with one item from each of its sequence arguments, but first, it tests both arguments. If either argument is empty, the function raises <span class="code">ValueError</span> rather than just returning an empty list as the list comprehension would normally do.</p>
<div data-type="tip">
<h1>Check Only What You Need To</h1>
<p>There is no need for <span class="code">cross_product</span> to check whether <span class="code">seq1</span> and <span class="code">seq2</span> are iterable: if either isn’t, the list comprehension itself raises the appropriate exception, presumably a <span class="code">TypeError</span>.</p>
</div>
<p>Once an exception is raised, by Python itself or with an explicit <span class="code"><strong>raise</strong></span> statement in your code, it is up to the caller to either handle it (with a suitable <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>except</strong></span> statement) or let it propagate further up the call stack.</p>
<div data-type="tip">
<h1>Don’t Use raise for Redundant Error Checks</h1>
<p>Use the <span class="code">raise</span> statement only to raise additional exceptions for cases that would normally be OK but that your specification defines to be errors. Do not use <span class="code">raise</span> to duplicate the same error checking that Python already (implicitly) does on your behalf.</p>
</div>
</div></section>
<section data-pdf-bookmark="The with Statement and Context Managers" data-type="sect1"><div class="sect1" id="the_with_statement_and_context_managers">
<h1>The with Statement and Context Managers</h1>
<p>The<a contenteditable="false" data-primary="as (with statement)" data-type="indexterm" id="idm44924573398112"/><a contenteditable="false" data-primary="exceptions" data-secondary="with statement and context managers" data-type="indexterm" id="Ewith06"/><a contenteditable="false" data-primary="with statement" data-type="indexterm" id="with06"/><a contenteditable="false" data-primary="context managers" data-type="indexterm" id="conman06"/> <span class="code"><strong>with</strong></span> statement is a compound statement with the following syntax:</p>
<pre data-code-language="python" data-type="programlisting">
<strong>with</strong> <em>expression</em> [<strong>as</strong> <em>varname</em>] [, ...]:
    <em>statement(s)</em>

<em># <span class="version">3.10+</span> multiple context managers for a with statement</em> 
<em># can be enclosed in parentheses</em>
<strong>with</strong> (<em>expression</em> [<strong>as</strong> <em>varname</em>], ...):
    <em>statement(s)</em></pre>
<p>The semantics of <span class="code"><strong>with</strong></span> are equivalent to:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">_normal_exit</code><code> </code><code class="o">=</code><code> </code><strong><code class="kc">True</code></strong><code>
</code><code class="n">_manager</code><code> </code><code class="o">=</code><code> </code><em><code class="n">expression</code></em><code>
</code><em><code class="n">varname</code></em><code> </code><code class="o">=</code><code> </code><code class="n">_manager</code><code class="o">.</code><code class="fm">__enter__</code><code class="p">(</code><code class="p">)</code><code>
</code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><em><code class="n">statement</code><code class="p">(</code><code class="n">s</code><code class="p">)</code></em><code>
</code><strong><code class="k">except</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="n">_normal_exit</code><code> </code><code class="o">=</code><code> </code><strong><code class="kc">False</code></strong><code>
</code><code>    </code><strong><code class="k">if</code><code> </code><code class="ow">not</code></strong><code> </code><code class="n">_manager</code><code class="o">.</code><code class="n">__exit_</code><code class="p">(</code><code class="o">*</code><code class="n">sys</code><code class="o">.</code><code class="n">exc_info</code><code class="p">(</code><code class="p">)</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">raise</code></strong><code>
</code><code>    </code><em><code class="c1"># note that exception does not propagate if __exit__ returns</code></em><code class="c1"> </code><code>
</code><code>    </code><em><code class="c1"># a true value</code></em><code>
</code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">if</code></strong><code> </code><code class="n">_normal_exit</code><code class="p">:</code><code>
</code><code>        </code><code class="n">_manager</code><code class="o">.</code><code class="fm">__exit__</code><code class="p">(</code><strong><code class="kc">None</code><code class="p">,</code><code> </code><code class="kc">None</code><code class="p">,</code><code> </code><code class="kc">None</code></strong><code class="p">)</code></pre>
<p>where <span class="code">_manager</span> and <span class="code">_normal_exit</span> are arbitrary internal names that are not used elsewhere in the current scope. If you omit the optional <span class="code"><strong>as</strong></span> <span class="code"><em>varname</em></span> part of the <span class="code"><strong>with</strong></span> clause, Python still calls <span class="code">_manager.__enter__</span>, but doesn’t bind the result to any name, and still calls <span class="code">_manager.__exit__</span> at block termination. The object returned by the <span class="code"><em>expression</em></span>, with methods <span class="code">__enter__</span> and <span class="code">__exit__</span>, is known as a <em>context manager</em>.</p>
<p class="pagebreak-before">The<a contenteditable="false" data-primary="resource acquisition is initialization (RAII)" data-type="indexterm" id="idm44924573299664"/><a contenteditable="false" data-primary="RAII (resource acquisition is initialization)" data-type="indexterm" id="idm44924573298560"/> <span class="code"><strong>with</strong></span> statement is the Python embodiment of the well-known C++ idiom <a href="https://oreil.ly/vROml">“resource acquisition is initialization” (RAII)</a>: you need only write context manager classes—that is, classes with two special methods, <span class="code">__enter__</span> and <span class="code">__exit__</span>. <span class="code">__enter__</span> must be callable without arguments. <span class="code">__exit__</span> must be callable with three arguments: all <span class="code"><strong>None</strong></span> when the body completes without propagating exceptions, and otherwise, the type, value, and traceback of the exception. This provides the same guaranteed finalization behavior as typical <span class="code">ctor/dtor</span> pairs have for <span class="code">auto</span> variables in C++ and <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>finally</strong></span> statements have in Python or Java. In addition, they can finalize differently depending on what exception, if any, propagates, and optionally block a propagating exception by returning a true value from <span class="code">__exit__</span>.</p>
<p>For example, here is a simple, purely illustrative way to ensure <span class="code">&lt;name&gt;</span> and <span class="code">&lt;/name&gt;</span> tags are printed around some other output (note that context manager classes often have lowercase names, rather than following the normal title case convention for class names):</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">class</code></strong><code> </code><code class="nc">enclosing_tag</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="fm">__init__</code><code class="p">(</code><code class="bp">self</code><code class="p">,</code><code> </code><code class="n">tagname</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="bp">self</code><code class="o">.</code><code class="n">tagname</code><code> </code><code class="o">=</code><code> </code><code class="n">tagname</code><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="fm">__enter__</code><code class="p">(</code><code class="bp">self</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="s1">&lt;</code><code class="si">{</code><code class="bp">self</code><code class="o">.</code><code class="n">tagname</code><code class="si">}</code><code class="s1">&gt;</code><code class="s1">'</code><code class="p">,</code><code> </code><code class="n">end</code><code class="o">=</code><code class="s1">'</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="fm">__exit__</code><code class="p">(</code><code class="bp">self</code><code class="p">,</code><code> </code><code class="n">etyp</code><code class="p">,</code><code> </code><code class="n">einst</code><code class="p">,</code><code> </code><code class="n">etb</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="s1">&lt;/</code><code class="si">{</code><code class="bp">self</code><code class="o">.</code><code class="n">tagname</code><code class="si">}</code><code class="s1">&gt;</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>
</code><em><code class="c1"># to be used as:</code></em><code>
</code><strong><code class="k">with</code></strong><code> </code><code class="n">enclosing_tag</code><code class="p">(</code><code class="s1">'</code><code class="s1">sometag</code><code class="s1">'</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><em><code class="c1"># ...statements printing output to be enclosed in</code></em><code>
</code><code>    </code><em><code class="c1"># a matched open/close `sometag` pair...</code></em></pre>
<p>A<a contenteditable="false" data-primary="contextlib module" data-type="indexterm" id="idm44924573156896"/><a contenteditable="false" data-primary="standard library modules" data-secondary="contextlib" data-type="indexterm" id="idm44924573155856"/> simpler way to build context managers is to use the <span class="code">contextmanager</span> decorator in the <span class="code">contextlib</span> module of the Python standard library. This decorator turns a generator function into a factory of context manager objects.</p>
<p>The <span class="code">contextlib</span> way to implement the <span class="code">enclosing_tag</span> context manager, having imported <span class="code">contextlib</span> earlier, is:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="nd">@contextlib</code><code class="o">.</code><code class="n">contextmanager</code><code>
</code><strong><code class="k">def</code></strong><code> </code><code class="nf">enclosing_tag</code><code class="p">(</code><code class="n">tagname</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="s1">&lt;</code><code class="si">{</code><code class="n">tagname</code><code class="si">}</code><code class="s1">&gt;</code><code class="s1">'</code><code class="p">,</code><code> </code><code class="n">end</code><code class="o">=</code><code class="s1">'</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">yield</code></strong><code>
</code><code>    </code><strong><code class="k">finally</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="s1">&lt;/</code><code class="si">{</code><code class="n">tagname</code><code class="si">}</code><code class="s1">&gt;</code><code class="s1">'</code><code class="p">)</code><code>
</code><em><code class="c1"># to be used the same way as before</code></em></pre>
<p><span class="code">contextlib</span> supplies, among others, the class and functions listed in <a data-type="xref" href="#commonly_used_classes_and_functions_in">Table 6-1</a>.</p>
<table class="border less_space pagebreak-before" id="commonly_used_classes_and_functions_in">
<caption><span class="label">Table 6-1. </span>Commonly used classes and functions in the <span class="code">contextlib</span> module</caption>
<tbody>
<tr>
<td class="width-20"><span class="code">AbstractContextManager</span></td>
<td><span class="code">AbstractContextManager</span><br/>
			An abstract base class with two overridable methods: <span class="code">__enter__</span>, which defaults to <span class="code"><strong>return</strong></span> <span class="code">self</span>, and <span class="code">__exit__</span>, which defaults to <span class="code"><strong>return</strong></span> <span class="code">None</span>.</td>
</tr>
<tr>
<td><span class="code">chdir</span></td>
<td><span class="code">chdir(<em>dir_path</em>)</span><br/>
<span class="version">3.11+</span> A<a contenteditable="false" data-primary="chdir (contextlib module)" data-type="indexterm" id="idm44924573041328"/> context manager whose <span class="code">__enter__</span> method saves the current working directory path and performs <span class="code">os.chdir(<em>dir_path</em>)</span>, and whose <span class="code">__exit__</span> method performs <span class="code">os.chdir(<em>saved_path</em>)</span>.</td>
</tr>
<tr>
<td><span class="code">closing</span></td>
<td><span class="code">closing(<em>something</em>)</span><br/>
			A<a contenteditable="false" data-primary="closing (contextlib module)" data-type="indexterm" id="idm44924573033344"/> context manager whose <span class="code">__enter__</span> method is <span class="code"><strong>return</strong></span> <span class="code"><em>something</em></span>, and whose <span class="code">__exit__</span> method calls <span class="code"><em>something</em></span><span class="code">.close()</span>.</td>
</tr>
<tr>
<td><span class="code">contextmanager</span></td>
<td><span class="code">contextmanager</span><br/>
			A<a contenteditable="false" data-primary="contextmanager (contextlib module)" data-type="indexterm" id="idm44924573025264"/> decorator that you apply to a generator to make it into a context manager.</td>
</tr>
<tr>
<td><span class="code">nullcontext</span></td>
<td><span class="code">nullcontext(<em>something</em>)</span><br/>
			A<a contenteditable="false" data-primary="nullcontext (contextlib module)" data-type="indexterm" id="idm44924573020960"/> context manager whose <span class="code">__enter__</span> method is <span class="code"><strong>return</strong></span> <span class="code"><em>something</em></span>, and whose <span class="code">__exit__</span> method does nothing.</td>
</tr>
<tr>
<td><span class="code">redirect_stderr</span></td>
<td><span class="code">redirect_stderr(<em>destination</em>)</span><br/>
			A<a contenteditable="false" data-primary="redirect_stderr (contextlib module)" data-type="indexterm" id="idm44924573013616"/> context manager that temporarily redirects, within the body of the <span class="code"><strong>with</strong></span> statement, <span class="code">sys.stderr</span> to the file or file-like object <span class="code"><em>destination</em></span>.</td>
</tr>
<tr>
<td><span class="code">redirect_stdout</span></td>
<td><span class="code">redirect_stdout(<em>destination</em>)</span><br/>
			A<a contenteditable="false" data-primary="redirect_stdout (contextlib module)" data-type="indexterm" id="idm44924573007056"/> context manager that temporarily redirects, within the body of the <span class="code"><strong>with</strong></span> statement, <span class="code">sys.stdout</span> to the file or file-like object <span class="code"><em>destination</em></span>.</td>
</tr>
<tr>
<td><span class="code">suppress</span></td>
<td><span class="code">suppress(<em>*exception_classes</em>)</span><br/>
			A <a contenteditable="false" data-primary="suppress (contextlib module)" data-type="indexterm" id="idm44924573000496"/>context manager that silently suppresses exceptions occurring in the body of the <span class="code"><strong>with</strong></span> statement of any of the classes listed in <span class="code"><em>exception_classes</em></span>. For instance, this function to delete a file ignores <span class="code">FileNotFoundError</span>:
			<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">delete_file</code><code class="p">(</code><code class="n">filename</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">with</code></strong><code> </code><code class="n">contextlib</code><code class="o">.</code><code class="n">suppress</code><code class="p">(</code><code class="ne">FileNotFoundError</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="n">os</code><code class="o">.</code><code class="n">remove</code><code class="p">(</code><code class="n">filename</code><code class="p">)</code></pre>
			Use sparingly, since silently suppressing exceptions is often bad practice.</td>
</tr>
</tbody>
</table>
<p>For more details, examples, “recipes,” and even more (somewhat abstruse) classes, see Python’s <a href="https://oreil.ly/Jwr_w">online docs</a>.<a contenteditable="false" data-primary="" data-startref="Ewith06" data-type="indexterm" id="idm44924572974848"/><a contenteditable="false" data-primary="" data-startref="with06" data-type="indexterm" id="idm44924572973632"/><a contenteditable="false" data-primary="" data-startref="conman06" data-type="indexterm" id="idm44924572972256"/></p>
</div></section>
<section data-pdf-bookmark="Generators and Exceptions" data-type="sect1"><div class="sect1" id="generators_and_exceptions">
<h1>Generators and Exceptions</h1>
<p>To<a contenteditable="false" data-primary="exceptions" data-secondary="generators and" data-type="indexterm" id="idm44924572969072"/><a contenteditable="false" data-primary="generators" data-type="indexterm" id="idm44924572943936"/> help generators cooperate with exceptions, <span class="code"><strong>yield</strong></span> statements are allowed inside <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>finally</strong></span> statements. Moreover, generator objects have two other relevant methods, <span class="code">throw</span> and <span class="code">close</span>. Given a generator object <span class="code"><em>g</em></span> built by calling a generator function, the <span class="code">throw</span> method’s signature is:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">g</code><code class="o">.</code><code class="n">throw</code><code class="p">(</code><em><code class="n">exc_value</code></em><code class="p">)</code></pre>
<p>When the generator’s caller calls <span class="code"><em>g</em></span><span class="code">.throw</span>, the effect is just as if a <span class="code"><strong>raise</strong></span> statement with the same argument executed at the spot of the <span class="code"><strong>yield</strong></span> at which generator <span class="code"><em>g</em></span> is suspended.</p>
<p>The generator method <span class="code">close</span> has no arguments; when the generator’s caller calls <span class="code"><em>g</em></span><span class="code">.close()</span>, the effect is like calling <span class="code"><em>g</em></span><span class="code">.throw(GeneratorExit())</span>.<sup><a data-type="noteref" href="ch06.xhtml#ch01fn78" id="ch01fn78-marker">1</a></sup> <span class="code">GeneratorExit</span> is a built-in exception class that inherits directly from <span class="code">BaseException</span>. Generators also have a finalizer (the special method <span class="code">__del__</span>) that implicitly calls <span class="code">close</span> when the generator object is garbage-collected.</p>
<p>If a generator raises or propagates a <span class="code">StopIteration</span> exception, Python turns the exception’s type into <span class="code">RuntimeError</span>.</p>
</div></section>
<section data-pdf-bookmark="Exception Propagation" data-type="sect1"><div class="sect1" id="exception_propagation">
<h1>Exception Propagation</h1>
<p>When<a contenteditable="false" data-primary="exceptions" data-secondary="exception propagation" data-type="indexterm" id="idm44924572894864"/> an exception is raised, the exception propagation mechanism takes control. The normal control flow of the program stops, and Python looks for a suitable exception handler. Python’s <span class="code"><strong>try</strong></span> statement establishes exception handlers via its <span class="code"><strong>except</strong></span> clauses. The handlers deal with exceptions raised in the body of the <span class="code"><strong>try</strong></span> clause, as well as exceptions propagating from functions called by that code, directly or indirectly. If an exception is raised within a <span class="code"><strong>try</strong></span> clause that has an applicable <span class="code"><strong>except</strong></span> handler, the <span class="code"><strong>try</strong></span> clause terminates and the handler executes. When the handler finishes, execution continues with the statement after the <span class="code"><strong>try</strong></span> statement (in the absence of any explicit change to the flow of control, such as a <span class="code"><strong>raise</strong></span> or <span class="code"><strong>return</strong></span> statement).</p>
<p>If the statement raising the exception is not within a <span class="code"><strong>try</strong></span> clause that has an applicable handler, the function containing the statement terminates, and the exception propagates “upward” along the stack of function calls to the statement that called the function. If the call to the terminated function is within a <span class="code"><strong>try</strong></span> clause that has an applicable handler, that <span class="code"><strong>try</strong></span> clause terminates, and the handler executes. Otherwise, the function containing the call terminates, and the propagation process repeats, <em>unwinding</em> the stack of function calls until an applicable handler is found.</p>
<p>If Python cannot find any applicable handler, by default the program prints an error message to the standard error stream (<span class="code">sys.stderr</span>). The error message includes a traceback that gives details about functions terminated during propagation. You can change Python’s default error-reporting behavior by setting <span class="code">sys.excepthook</span> (covered in <a data-type="xref" href="ch08.xhtml#functions_and_attributes_of_the_sys_mod">Table 8-3</a>). After error reporting, Python goes back to the interactive session, if any, or terminates if execution was not interactive. When the exception type is <span class="code">SystemExit</span>, termination is silent and ends the interactive session, if any.</p>
<p>Here are some functions to show exception propagation at work:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">f</code><code class="p">(</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">in f, before 1/0</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><code class="mi">1</code><code class="o">/</code><code class="mi">0</code><code>    </code><em><code class="c1"># raises a ZeroDivisionError exception</code></em><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">in f, after 1/0</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">def</code></strong><code> </code><code class="nf">g</code><code class="p">(</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">in g, before f()</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><code class="n">f</code><code class="p">(</code><code class="p">)</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">in g, after f()</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code class="k">def</code></strong><code> </code><code class="nf">h</code><code class="p">(</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">in h, before g()</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="n">g</code><code class="p">(</code><code class="p">)</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">in h, after g()</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="ne">ZeroDivisionError</code><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">ZD exception caught</code><code class="s1">'</code><code class="p">)</code><code>
</code><code>    </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">function h ends</code><code class="s1">'</code><code class="p">)</code></pre>
<p>Calling the <span class="code">h</span> function prints the following:</p>
<pre data-type="programlisting">
<strong>in h, before g()</strong>
<strong>in g, before f()</strong>
<strong>in f, before 1/0</strong>
<strong>ZD exception caught</strong>
<strong>function h ends</strong></pre>
<p>That is, none of the “after” <span class="code">print</span> statements execute, since the flow of exception propagation cuts them off.</p>
<p>The function <span class="code">h</span> establishes a <span class="code"><strong>try</strong></span> statement and calls the function <span class="code">g</span> within the <span class="code"><strong>try</strong></span> clause. <span class="code">g</span>, in turn, calls <span class="code">f</span>, which performs a division by <span class="code">0</span>, raising an exception of type <span class="code">ZeroDivisionError</span>. The exception propagates all the way back to the <span class="code"><strong>except</strong></span> clause in <span class="code">h</span>. The functions <span class="code">f</span> and <span class="code">g</span> terminate during the exception propagation phase, which is why neither of their “after” messages is printed. The execution of <span class="code">h</span>’s <span class="code"><strong>try</strong></span> clause also terminates during the exception propagation phase, so its “after” message isn’t printed either. Execution continues after the handler, at the end of <span class="code">h</span>’s <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>except</strong></span> block.</p>
</div></section>
<section data-pdf-bookmark="Exception Objects" data-type="sect1"><div class="sect1" id="exception_objects">
<h1>Exception Objects</h1>
<p>Exceptions<a contenteditable="false" data-primary="exceptions" data-secondary="exception objects" data-type="indexterm" id="Eexobj06"/> are instances of <span class="code">BaseException</span> (more specifically, instances of one of its subclasses). <a data-type="xref" href="#attributes_and_methods_of_the_baseexcep">Table 6-2</a> lists the attributes and methods of <span class="code">BaseException</span>.</p>
<table class="border" id="attributes_and_methods_of_the_baseexcep">
<caption><span class="label">Table 6-2. </span>Attributes and methods of the <span class="code">BaseException</span> class</caption>
<tbody>
<tr>
<td><span class="code">__cause__</span></td>
<td><span class="code"><em>exc</em></span><span class="code">.__cause__</span><br/>
			Returns the parent exception of an exception raised using <span class="code"><strong>raise</strong></span> <span class="code"><strong>from</strong></span>.</td>
</tr>
<tr>
<td><span class="code">__notes__</span></td>
<td><span class="code"><em>exc</em></span><span class="code">.__notes__</span><br/>
<span class="version">3.11+</span> Returns a list of <span class="code">str</span>s added to the exception using <span class="code">add_note</span>. This attribute only exists if <span class="code">add_note</span> has been called at least once, so the safe way to access this list is with <span class="code">getattr(<em>exc</em>, '__notes__', [])</span>.</td>
</tr>
<tr>
<td><span class="code">add_note</span></td>
<td><span class="code"><em>exc</em></span><span class="code">.add_note(<em>note</em>)</span><br/>
<span class="version">3.11+</span> Appends the <span class="code">str</span> <span class="code"><em>note</em></span> to the notes on this exception. These notes are shown after the traceback when displaying the exception.</td>
</tr>
<tr>
<td><span class="code">args</span></td>
<td><span class="code"><em>exc.</em></span><span class="code">args</span><br/>
			Returns a tuple of the arguments used to construct the exception. This error-specific information is useful for diagnostic or recovery purposes. Some exception classes interpret <span class="code">args</span> and set convenient named attributes on the classes’ instances.</td>
</tr>
<tr>
<td><span class="code">wi⁠t⁠h⁠_​t⁠r⁠a⁠ceback</span></td>
<td><span class="code"><em>exc</em></span><span class="code">.with_traceback(<em>tb</em>)</span><br/>
			Returns a new exception, replacing the original exception’s traceback with the new traceback <span class="code"><em>tb</em></span>, or with no traceback if <span class="code"><em>tb</em></span> is <span class="code"><strong>None</strong></span>. Can be used to trim the original traceback to remove internal library function call frames.</td>
</tr>
</tbody>
</table>
<section data-pdf-bookmark="The Hierarchy of Standard Exceptions" data-type="sect2"><div class="sect2" id="the_hierarchy_of_standard_exceptions">
<h2>The Hierarchy of Standard Exceptions</h2>
<p>As<a contenteditable="false" data-primary="standard exceptions" data-secondary="hierarchy of" data-type="indexterm" id="idm44924572697840"/><a contenteditable="false" data-primary="except clause" data-type="indexterm" id="idm44924572695712"/> mentioned previously, exceptions are instances of subclasses of <span class="code">BaseException</span>. The inheritance structure of exception classes is important, as it determines which <span class="code"><strong>except</strong></span> clauses handle which exceptions. Most exception classes extend the class <span class="code">Exception</span>; however, the classes <span class="code">KeyboardInterrupt</span>, <span class="code">GeneratorExit</span>, and <span class="code">SystemExit</span> inherit directly from <span class="code">BaseException</span> and are not subclasses of <span class="code">Exception</span>. Thus, a handler clause <span class="code"><strong>except</strong></span> <span class="code">Exception</span> <span class="code"><strong>as</strong></span> <span class="code">e</span> does not catch <span class="code">KeyboardInterrupt</span>, <span class="code">GeneratorExit</span>, or <span class="code">SystemExit</span> (we covered exception handlers in <a data-type="xref" href="#trysolidusexcept">“try/except”</a> and <span class="code">GeneratorExit</span> in <a data-type="xref" href="#generators_and_exceptions">“Generators and Exceptions”</a>). Instances of <span class="code">SystemExit</span> are normally raised via the <span class="code">exit</span> function in the <span class="code">sys</span> module (covered in <a data-type="xref" href="ch08.xhtml#functions_and_attributes_of_the_sys_mod">Table 8-3</a>). When the user hits Ctrl-C, Ctrl-Break, or other interrupting keys on their keyboard, that raises <span class="code">KeyboardInterrupt</span>.</p>
<p>The hierarchy of built-in exception classes is, roughly:</p>
<pre data-type="programlisting">
BaseException
  Exception
    AssertionError, AttributeError, BufferError, EOFError,
    MemoryError, ReferenceError, OsError, StopAsyncIteration,
    StopIteration, SystemError, TypeError
    ArithmeticError (abstract)
      OverflowError, ZeroDivisionError
    ImportError
      ModuleNotFoundError, ZipImportError
    LookupError (abstract)
      IndexError, KeyError
    NameError
      UnboundLocalError
    OSError
      ...
    RuntimeError
      RecursionError
      NotImplementedError
    SyntaxError
      IndentationError
        TabError
    ValueError
      UnsupportedOperation
      UnicodeError
        UnicodeDecodeError, UnicodeEncodeError,
        UnicodeTranslateError
    Warning
      ...
  GeneratorExit
  KeyboardInterrupt
  SystemExit</pre>
<p>There are other exception subclasses (in particular, <span class="code">Warning</span> and <span class="code">OSError</span> have many, whose omission is indicated here with ellipses), but this is the gist. A complete list is available in Python’s <a href="https://oreil.ly/pLihr">online docs</a>.</p>
<p>The classes marked “(abstract)” are never instantiated directly; their purpose is to make it easier for you to specify <span class="code"><strong>except</strong></span> clauses that handle a range of related errors.</p>
</div></section>
<section data-pdf-bookmark="Standard Exception Classes" data-type="sect2"><div class="sect2" id="standard_exception_classe">
<h2>Standard Exception Classes</h2>
<p><a data-type="xref" href="#standard_exception_classes">Table 6-3</a> lists<a contenteditable="false" data-primary="standard exceptions" data-secondary="classes raised by runtime errors" data-type="indexterm" id="idm44924572669824"/><a contenteditable="false" data-primary="exceptions" data-secondary="standard exceptions" data-type="indexterm" id="idm44924572668384"/> exception classes raised by common runtime errors.</p>
<table class="border" id="standard_exception_classes">
<caption><span class="label">Table 6-3. </span>Standard exception classes</caption>
<thead>
<tr>
<th class="width-20">Exception class</th>
<th>Raised when</th>
</tr>
</thead>
<tbody>
<tr>
<td><span class="code">AssertionError</span></td>
<td>An <span class="code"><strong>assert</strong></span> statement failed.</td>
</tr>
<tr>
<td><span class="code">AttributeError</span></td>
<td>An attribute reference or assignment failed.</td>
</tr>
<tr>
<td><span class="code">ImportError</span></td>
<td>An <span class="code"><strong>import</strong></span> or <span class="code"><strong>from</strong></span><span class="code">...</span><span class="code"><strong>import</strong></span> statement (covered in <a data-type="xref" href="ch07.xhtml#the_import_statement">“The import Statement”</a>) couldn’t find the module to import (in this case, what Python raises is actually an instance of <span class="code">ImportError</span>’s subclass <span class="code">ModuleNotFoundError</span>), or couldn’t find a name to be imported from the module.</td>
</tr>
<tr>
<td><span class="code">IndentationError</span></td>
<td>The parser encountered a syntax error due to incorrect indentation. Subclasses <span class="code">SyntaxError</span>.</td>
</tr>
<tr>
<td><span class="code">IndexError</span></td>
<td>An integer used to index a sequence is out of range (using a noninteger as a sequence index raises <span class="code">TypeError</span>). Subclasses <span class="code">LookupError</span>.</td>
</tr>
<tr>
<td><span class="code">KeyboardInterrupt</span></td>
<td>The user pressed the interrupt key combination (Ctrl-C, Ctrl-Break, Delete, or others, depending on the platform’s handling of the keyboard).</td>
</tr>
<tr>
<td><span class="code">KeyError</span></td>
<td>A key used to index a mapping is not in the mapping. Subclasses <span class="code">LookupError</span>.</td>
</tr>
<tr>
<td><span class="code">MemoryError</span></td>
<td>An operation ran out of memory.</td>
</tr>
<tr>
<td><span class="code">NameError</span></td>
<td>A name was referenced, but it was not bound to any variable in the current scope.</td>
</tr>
<tr>
<td><span class="code">N⁠o⁠t⁠I⁠m⁠p⁠l⁠e⁠m⁠e⁠n⁠t⁠e⁠d​E⁠r⁠r⁠o⁠r</span></td>
<td>Raised by abstract base classes to indicate that a concrete subclass must override a method.</td>
</tr>
<tr>
<td><span class="code">OSError</span></td>
<td>Raised by functions in the module <span class="code">os</span> (covered in <a data-type="xref" href="ch11.xhtml#the_os_module">“The os Module”</a> and <a data-type="xref" href="ch15.xhtml#running_other_programs_with_the_os_modu">“Running Other Programs with the os Module”</a>) to indicate platform-dependent errors. <span class="code">OSError</span> has many subclasses, covered in the following subsection.</td>
</tr>
<tr>
<td><span class="code">RecursionError</span></td>
<td>Python detected that the recursion depth has been exceeded. Subclasses <span class="code">RuntimeError</span>.</td>
</tr>
<tr>
<td><span class="code">RuntimeError</span></td>
<td>Raised for any error or anomaly not otherwise classified.</td>
</tr>
<tr>
<td><span class="code">SyntaxError</span></td>
<td>Python’s parser encountered a syntax error.</td>
</tr>
<tr>
<td><span class="code">SystemError</span></td>
<td>Python has detected an error in its own code, or in an extension module. Please report this to the maintainers of your Python version, or of the extension in question, including the error message, the exact Python version (<span class="code">sys.version</span>), and, if possible, your program’s source code.</td>
</tr>
<tr>
<td><span class="code">TypeError</span></td>
<td>An operation or function was applied to an object of an inappropriate type.</td>
</tr>
<tr>
<td><span class="code">UnboundLocalError</span></td>
<td>A reference was made to a local variable, but no value is currently bound to that local variable. Subclasses <span class="code">NameError</span>.</td>
</tr>
<tr>
<td><span class="code">UnicodeError</span></td>
<td>An error occurred while converting Unicode (i.e., a <span class="code">str</span>) to a byte string, or vice versa. Subclasses <span class="code">ValueError</span>.</td>
</tr>
<tr>
<td><span class="code">ValueError</span></td>
<td>An operation or function was applied to an object that has a correct type but an inappropriate value, and nothing more specific (e.g., <span class="code">KeyError</span>) applies.</td>
</tr>
<tr>
<td><span class="code">ZeroDivisionError</span></td>
<td>A divisor (the righthand operand of a <span class="code">/</span>, <span class="code">//</span>, or <span class="code">%</span> operator, or the second argument to the built-in function <span class="code">divmod</span>) is <span class="code">0</span>. Subclasses <span class="code">ArithmeticError</span>.</td>
</tr>
</tbody>
</table>
<section data-pdf-bookmark="OSError subclasses" data-type="sect3"><div class="sect3" id="oserror_subclasses">
<h3>OSError subclasses</h3>
<p><span class="code">OSError</span> represents<a contenteditable="false" data-primary="standard exceptions" data-secondary="OSError subclasses" data-type="indexterm" id="idm44924572604320"/><a contenteditable="false" data-primary="OSError" data-type="indexterm" id="idm44924572602912"/> errors detected by the operating system. To handle such errors more elegantly, <span class="code">OSError</span> has many subclasses, whose instances are what actually get raised; for a complete list, see Python’s <a href="https://oreil.ly/3vJ3W">online docs</a>.</p>
<p>For example, consider this task: try to read and return the contents of a certain file, return a default string if the file does not exist, and propagate any other exception that makes the file unreadable (except for the file not existing). Using an existing <span class="code">OSError</span> subclass, you can accomplish the task quite simply:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">read_or_default</code><code class="p">(</code><code class="n">filepath</code><code class="p">,</code><code> </code><code class="n">default</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">with</code></strong><code> </code><code class="nb">open</code><code class="p">(</code><code class="n">filepath</code><code class="p">)</code><code> </code><strong><code class="k">as</code></strong><code> </code><code class="n">f</code><code class="p">:</code><code>
</code><code>            </code><strong><code class="k">return</code></strong><code> </code><code class="n">f</code><code class="o">.</code><code class="n">read</code><code class="p">(</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="ne">FileNotFoundError</code><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="n">default</code></pre>
<p>The <span class="code">FileNotFoundError</span> subclass of <span class="code">OSError</span> makes this kind of common task simple and direct to express in code.</p>
</div></section>
<section data-pdf-bookmark="Exceptions “wrapping” other exceptions or tracebacks" data-type="sect3"><div class="sect3" id="exceptions_quotation_markwrappingquotat">
<h3>Exceptions “wrapping” other exceptions or tracebacks</h3>
<p>Sometimes, you cause an exception while trying to handle another. To let you clearly diagnose this issue, each exception instance holds its own traceback object; you can make another exception instance with a different traceback with the <span class="code">with_traceback</span> method.</p>
<p>Moreover, Python automatically stores which exception it’s handling as the <span class="code">__context__</span> attribute of any further exception raised during the handling (unless you set the exception’s <span class="code">__suppress_context__</span> attribute to <span class="code"><strong>True</strong></span> with the <span class="code"><strong>raise</strong></span><span class="code">...</span><span class="code"><strong>from</strong></span> statement, which we cover shortly). If the new exception propagates, Python’s error message uses that exception’s <span class="code">__context__</span> attribute to show details of the problem. For example, take the (deliberately!) broken code:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="mi">1</code><code class="o">/</code><code class="mi">0</code><code>
</code><strong><code class="k">except</code></strong><code> </code><code class="ne">ZeroDivisionError</code><code class="p">:</code><code>
</code><code>    </code><code class="mi">1</code><code class="o">+</code><code class="s1">'</code><code class="s1">x</code><code class="s1">'</code></pre>
<p>The error displayed is:</p>
<pre data-type="programlisting">
<strong>Traceback (most recent call last):</strong>
<strong>  File "&lt;stdin&gt;", line 1, in &lt;module&gt;</strong>
<strong>ZeroDivisionError: division by zero</strong>

<strong>During handling of the above exception, another exception occurred:</strong>

<strong>Traceback (most recent call last):</strong>
<strong>  File "&lt;stdin&gt;", line 3, in &lt;module&gt;</strong>
<strong>TypeError: unsupported operand type(s) for +: 'int' and 'str'</strong></pre>
<p>Thus, Python clearly displays both exceptions, the original and the intervening one.</p>
<p>To get more control over the error display, you can, if you wish, use the <span class="code"><strong>raise</strong></span><span class="code">...</span><span class="code"><strong>from</strong></span> statement. When you execute <span class="code"><strong>raise</strong></span> <span class="code"><em>e</em></span> <span class="code"><strong>from</strong></span> <span class="code"><em>ex</em></span>, both <span class="code"><em>e</em></span> and <span class="code"><em>ex</em></span> are exception objects: <span class="code"><em>e</em></span> is the one that propagates, and <span class="code"><em>ex</em></span> is its “cause.” Python records <span class="code"><em>ex</em></span> as the value of <span class="code"><em>e.__cause__</em></span>, and sets <span class="code"><em>e.</em></span><span class="code">__suppress_context__</span> to true. (Alternatively, <span class="code"><em>ex</em></span> can be <span class="code"><strong>None</strong></span>: then, Python sets <span class="code"><em>e.__cause__</em></span> to <span class="code"><strong>None</strong></span>, but still sets <span class="code"><em>e.</em></span><span class="code">__suppress_context__</span> to true, and thus leaves <span class="code"><em>e.</em></span><span class="code">__context__</span> alone).</p>
<p>As another example, here’s a class implementing a mock filesystem directory using a Python dict, with the filenames as the keys and the file contents as the values:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">class</code></strong><code> </code><code class="nc">FileSystemDirectory</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="fm">__init__</code><code class="p">(</code><code class="bp">self</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="bp">self</code><code class="o">.</code><code class="n">_files</code><code> </code><code class="o">=</code><code> </code><code class="p">{</code><code class="p">}</code><code>
</code><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="nf">write_file</code><code class="p">(</code><code class="bp">self</code><code class="p">,</code><code> </code><code class="n">filename</code><code class="p">,</code><code> </code><code class="n">contents</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="bp">self</code><code class="o">.</code><code class="n">_files</code><code class="p">[</code><code class="n">filename</code><code class="p">]</code><code> </code><code class="o">=</code><code> </code><code class="n">contents</code><code>
</code><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="nf">read_file</code><code class="p">(</code><code class="bp">self</code><code class="p">,</code><code> </code><code class="n">filename</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>            </code><code class="k">return</code><code> </code><code class="bp">self</code><code class="o">.</code><code class="n">_files</code><code class="p">[</code><code class="n">filename</code><code class="p">]</code><code>
</code><code>        </code><strong><code class="k">except</code></strong><code> </code><code class="ne">KeyError</code><code class="p">:</code><code>
</code><code>            </code><strong><code class="k">raise</code></strong><code> </code><code class="ne">FileNotFoundError</code><code class="p">(</code><code class="n">filename</code><code class="p">)</code></pre>
<p>When <span class="code">read_file</span> is called with a nonexistent filename, the access to the <span class="code">self._files</span> <span class="code">dict</span> raises <span class="code">KeyError</span>. Since this code is intended to emulate a filesystem directory, <span class="code">read_file</span> catches the <span class="code">KeyError</span> and raises <span class="code">FileNotFoundError</span> instead.</p>
<p>As is, accessing a nonexistent file named <span class="code">'data.txt'</span> will output an exception message similar to:</p>
<pre data-type="programlisting">
<strong>Traceback (most recent call last):</strong>
<strong>  File "C:\dev\python\faux_fs.py", line 11, in read_file</strong>
<strong>    return self._files[filename]</strong>
<strong>KeyError: 'data.txt'</strong>

<strong>During handling of the above exception, another exception occurred:</strong>

<strong>Traceback (most recent call last):</strong>
<strong>  File "C:\dev\python\faux_fs.py", line 20, in &lt;module&gt;</strong>
<strong>    print(fs.read_file("data.txt"))</strong>
<strong>  File "C:\dev\python\faux_fs.py", line 13, in read_file</strong>
<strong>    raise FileNotFoundError(filename)</strong>
<strong>FileNotFoundError: data.txt</strong></pre>
<p>This exception report shows both the <span class="code">KeyError</span> and the <span class="code">FileNotFoundError</span>. To suppress the internal <span class="code">KeyError</span> exception (to hide implementation details of <span class="code">FileSystemDirectory</span>), we change the <span class="code"><strong>raise</strong></span> statement in <span class="code">read_file</span> to:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code>    </code><code class="k">raise</code></strong><code> </code><code class="ne">FileNotFoundError</code><code class="p">(</code><code class="n">filename</code><code class="p">)</code><code> </code><strong><code class="kn">from</code><code> </code><code class="bp">None</code></strong></pre>
<p>Now the exception only shows the <span class="code">FileNotFoundError</span> information:</p>
<pre data-type="programlisting">
<strong>Traceback (most recent call last):</strong>
<strong>  File "C:\dev\python\faux_fs.py", line 20, in &lt;module&gt;</strong>
<strong>    print(fs.read_file("data.txt"))</strong>
<strong>  File "C:\dev\python\faux_fs.py", line 13, in read_file</strong>
<strong>    raise FileNotFoundError(filename) from None</strong>
<strong>FileNotFoundError: data.txt</strong></pre>
<p>For details and motivations regarding exception chaining and embedding, see <a href="https://oreil.ly/wE9rL">PEP 3134</a>.<a contenteditable="false" data-primary="" data-startref="Eexobj06" data-type="indexterm" id="idm44924572332512"/></p>
</div></section>
</div></section>
</div></section>
<section data-pdf-bookmark="Custom Exception Classes" data-type="sect1"><div class="sect1" id="custom_exception_classes">
<h1>Custom Exception Classes</h1>
<p>You<a contenteditable="false" data-primary="exceptions" data-secondary="custom classes" data-type="indexterm" id="Ecustom06"/><a contenteditable="false" data-primary="custom exception classes" data-type="indexterm" id="custexc06"/> can extend any of the standard exception classes in order to define your own exception class. Often, such a subclass adds nothing more than a docstring:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">class</code></strong><code> </code><code class="nc">InvalidAttributeError</code><code class="p">(</code><code class="ne">AttributeError</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><em><code class="sd">"""Used to indicate attributes that could never be valid."""</code></em></pre>
<div data-type="tip">
<h1>An Empty Class or Function Should Have a Docstring</h1>
<p>As covered in <a data-type="xref" href="ch03.xhtml#the_pass_statement">“The pass Statement”</a>, you don’t need a <span class="code">pass</span> statement to make up the body of a class. The docstring (which you should always write, to document the class’s purpose if nothing else!) is enough to keep Python happy. Best practice for all “empty” classes (regardless of whether they are exception classes), just like for all “empty” functions, is usually to have a docstring and no <span class="code"><strong>pass</strong></span> <span class="keep-together">statement</span>.</p>
</div>
<p>Given the semantics of <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>except</strong></span>, raising an instance of a custom exception class such as <span class="code">InvalidAttributeError</span> is almost the same as raising an instance of its standard exception superclass, <span class="code">AttributeError</span>, but with some advantages. Any <span class="code"><strong>except</strong></span> clause that can handle <span class="code">AttributeError</span> can handle <span class="code">InvalidAttributeError</span> just as well. In addition, client code that knows about your <span class="code">InvalidAttributeError</span> custom exception class can handle it specifically, without having to handle all other cases of <span class="code">AttributeError</span> when it is not prepared for those. For example, suppose you write code like the following:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">class</code></strong><code> </code><code class="nc">SomeFunkyClass</code><code class="p">:</code><code>
</code><code>    </code><em><code class="sd">"""much hypothetical functionality snipped"""</code></em><code>
</code><code>    </code><strong><code class="k">def</code></strong><code> </code><code class="fm">__getattr__</code><code class="p">(</code><code class="bp">self</code><code class="p">,</code><code> </code><code class="n">name</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><em><code class="sd">"""only clarifies the kind of attribute error"""</code></em><code>
</code><code>        </code><strong><code class="k">if</code></strong><code> </code><code class="n">name</code><code class="o">.</code><code class="n">startswith</code><code class="p">(</code><code class="s1">'</code><code class="s1">_</code><code class="s1">'</code><code class="p">)</code><code class="p">:</code><code>
</code><code>            </code><strong><code class="k">raise</code></strong><code> </code><code class="n">InvalidAttributeError</code><code class="p">(</code><code>
</code><code>                </code><code class="sa">f</code><code class="s1">'</code><code class="s1">Unknown private attribute </code><code class="si">{</code><code class="n">name</code><code class="si">!r}</code><code class="s1">'</code><code>
</code><code>            </code><code class="p">)</code><code>
</code><code>        </code><strong><code class="k">else</code></strong><code class="p">:</code><code>
</code><code>            </code><strong><code class="k">raise</code></strong><code> </code><code class="ne">AttributeError</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="s1">Unknown attribute </code><code class="si">{</code><code class="n">name</code><code class="si">!r}</code><code class="s1">'</code><code class="p">)</code></pre>
<p>Now, client code can, if it so chooses, be more selective in its handlers. For example:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">s</code><code> </code><code class="o">=</code><code> </code><code class="n">SomeFunkyClass</code><code class="p">(</code><code class="p">)</code><code>
</code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>    </code><code class="n">value</code><code> </code><code class="o">=</code><code> </code><code class="nb">getattr</code><code class="p">(</code><code class="n">s</code><code class="p">,</code><code> </code><code class="n">thename</code><code class="p">)</code><code>
</code><strong><code class="k">except</code></strong><code> </code><code class="n">InvalidAttributeError</code><code> </code><code class="k">as</code><code> </code><code class="n">err</code><code class="p">:</code><code>
</code><code>    </code><code class="n">warnings</code><code class="o">.</code><code class="n">warn</code><code class="p">(</code><code class="nb">str</code><code class="p">(</code><code class="n">err</code><code class="p">)</code><code class="p">,</code><code> </code><code class="n">stacklevel</code><code class="o">=</code><code class="mi">2</code><code class="p">)</code><code>
</code><code>    </code><code class="n">value</code><code> </code><code class="o">=</code><code> </code><strong><code class="kc">None</code></strong><code>
</code><em><code class="c1"># other cases of AttributeError just propagate, as they're unexpected</code></em></pre>
<div data-type="tip">
<h1>Use Custom Exception Classes</h1>
<p>It’s an excellent idea to define, and raise, instances of custom exception classes in your modules, rather than plain standard exceptions. By using custom exception classes that extend standard ones, you make it easier for callers of your module’s code to handle exceptions that come from your module separately from others, if they choose to.</p>
</div>
<section data-pdf-bookmark="Custom Exceptions and Multiple Inheritance" data-type="sect2"><div class="sect2" id="custom_exceptions_and_multiple_inherita">
<h2>Custom Exceptions and Multiple Inheritance</h2>
<p>An<a contenteditable="false" data-primary="multiple inheritance" data-type="indexterm" id="idm44924569026848"/><a contenteditable="false" data-primary="inheritance" data-secondary="custom exceptions and multiple inheritance" data-type="indexterm" id="idm44924569025712"/> effective approach to the use of custom exceptions is to multiply inherit exception classes from your module’s special custom exception class and a standard exception class, as in the following snippet:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">class</code></strong><code> </code><code class="nc">CustomAttributeError</code><code class="p">(</code><code class="n">CustomException</code><code class="p">,</code><code> </code><code class="ne">AttributeError</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><em><code class="sd">"""An AttributeError which is ALSO a CustomException."""</code></em></pre>
<p>Now, an instance of <span class="code">CustomAttributeError</span> can only be raised explicitly and deliberately, showing an error related specifically to your code that <em>also</em> happens to be an <span class="code">AttributeError</span>. When your code raises an instance of <span class="code">CustomAttributeError</span>, that exception can be caught by calling code that’s designed to catch all cases of <span class="code">AttributeError</span> as well as by code that’s designed to catch all exceptions raised only, specifically, by your module.</p>
<div data-type="tip">
<h1>Use Multiple Inheritance for Custom Exceptions</h1>
<p>Whenever you must decide whether to raise an instance of a specific standard exception, such as <span class="code">AttributeError</span>, or of a custom exception class you define in your module, consider this multiple inheritance approach, which, in this book’s authors’ opinion,<sup><a data-type="noteref" href="ch06.xhtml#ch01fn79" id="ch01fn79-marker">2</a></sup> gives you the best of both worlds in such cases. Make sure you clearly document this aspect of your module, because the technique, although handy, is not widely used. Users of your module may not expect it unless you clearly and explicitly document what you are doing.</p>
</div>
</div></section>
<section data-pdf-bookmark="Other Exceptions Used in the Standard Library" data-type="sect2"><div class="sect2" id="other_exceptions_used_in_the_standard_l">
<h2>Other Exceptions Used in the Standard Library</h2>
<p>Many modules in Python’s standard library define their own exception classes, which are equivalent to the custom exception classes that your own modules can define. Typically, all functions in such standard library modules may raise exceptions of such classes, in addition to exceptions in the standard hierarchy covered in <a data-type="xref" href="#standard_exception_classe">“Standard Exception Classes”</a>. We cover the main cases of such exception classes throughout the rest of this book, in chapters covering the standard library modules that supply and may raise them.<a contenteditable="false" data-primary="" data-startref="custexc06" data-type="indexterm" id="idm44924568952224"/><a contenteditable="false" data-primary="" data-startref="Ecustom06" data-type="indexterm" id="idm44924568950880"/></p>
</div></section>
</div></section>
<section data-pdf-bookmark="ExceptionGroup and except*" data-type="sect1"><div class="sect1" id="exceptiongroup_and_exceptasterisk">
<h1>ExceptionGroup and except*</h1>
<p><span class="version">3.11+</span> In<a contenteditable="false" data-primary="exceptions" data-secondary="ExceptionGroup and except*" data-type="indexterm" id="EXgrpstar06"/> some circumstances, such as when performing validation of some input data against multiple criteria, it is useful to be able to raise more than a single exception at once. Python 3.11 introduced a mechanism to raise multiple exceptions at once using an <span class="code">ExceptionGroup</span> instance and to process more than one exception using an <span class="code"><strong>except*</strong></span> form in place of <span class="code"><strong>except</strong></span>.</p>
<p>To raise <span class="code">ExceptionGroup</span>, the validating code captures multiple <span class="code">Exception</span>s into a list and then raises an <span class="code">ExceptionGroup</span> that is constructed using that list. Here is some code that searches for misspelled and invalid words, and raises an <span class="code keep-together">ExceptionGroup</span> containing all of the found errors:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">class</code></strong><code> </code><code class="nc">GrammarError</code><code class="p">(</code><code class="ne">Exception</code><code class="p">)</code><code class="p">:</code><code>
</code><strong><code>   </code></strong><code> </code><em><code class="sd">"""Base exception for grammar checking"""</code></em><code>
</code><strong><code>    </code><code class="k">def</code></strong><code> </code><code class="fm">__init__</code><code class="p">(</code><code class="bp">self</code><code class="p">,</code><code> </code><code class="n">found</code><code class="p">,</code><code> </code><code class="n">suggestion</code><code class="p">)</code><code class="p">:</code><code>
</code><code>        </code><code class="bp">self</code><code class="o">.</code><code class="n">found</code><code> </code><code class="o">=</code><code> </code><code class="n">found</code><code>
</code><code>        </code><code class="bp">self</code><code class="o">.</code><code class="n">suggestion</code><code> </code><code class="o">=</code><code> </code><code class="n">suggestion</code><code>
</code><code>
</code><strong><code class="k">class</code></strong><code> </code><code class="nc">InvalidWordError</code><code class="p">(</code><code class="n">GrammarError</code><code class="p">)</code><code class="p">:</code><code>
</code><strong><code>  </code></strong><code>  </code><em><code class="sd">"""Misused or nonexistent word"""</code></em><code>
</code><code>
</code><strong><code class="k">class</code></strong><code> </code><code class="nc">MisspelledWordError</code><code class="p">(</code><code class="n">GrammarError</code><code class="p">)</code><code class="p">:</code><code>
</code><strong><code>   </code></strong><code> </code><em><code class="sd">"""Spelling error"""</code></em><code>
</code><code>
</code><code class="n">invalid_words</code><code> </code><code class="o">=</code><code> </code><code class="p">{</code><code>
</code><code>    </code><code class="s1">'</code><code class="s1">irregardless</code><code class="s1">'</code><code class="p">:</code><code> </code><code class="s1">'</code><code class="s1">regardless</code><code class="s1">'</code><code class="p">,</code><code>
</code><code>    </code><code class="s2">"</code><code class="s2">ain</code><code class="s2">'</code><code class="s2">t</code><code class="s2">"</code><code class="p">:</code><code> </code><code class="s2">"</code><code class="s2">isn</code><code class="s2">'</code><code class="s2">t</code><code class="s2">"</code><code class="p">,</code><code>
</code><code class="p">}</code><code> </code><code>
</code><code class="n">misspelled_words</code><code> </code><code class="o">=</code><code> </code><code class="p">{</code><code>
</code><code>    </code><code class="s1">'</code><code class="s1">tacco</code><code class="s1">'</code><code class="p">:</code><code> </code><code class="s1">'</code><code class="s1">taco</code><code class="s1">'</code><code class="p">,</code><code>
</code><code class="p">}</code><code>
</code><code>
</code><strong><code class="k">def</code></strong><code> </code><code class="nf">check_grammar</code><code class="p">(</code><code class="n">s</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><code class="n">exceptions</code><code> </code><code class="o">=</code><code> </code><code class="p">[</code><code class="p">]</code><code>
</code><strong><code>    </code><code class="k">for</code></strong><code> </code><code class="n">word</code><code> </code><strong><code class="ow">in</code></strong><code> </code><code class="n">s</code><code class="o">.</code><code class="n">lower</code><code class="p">(</code><code class="p">)</code><code class="o">.</code><code class="n">split</code><code class="p">(</code><code class="p">)</code><code class="p">:</code><code>
</code><strong><code>        </code><code class="k">if</code></strong><code> </code><code class="p">(</code><code class="n">suggestion</code><code> </code><code class="o">:=</code><code> </code><code class="n">invalid_words</code><code class="o">.</code><code class="n">get</code><code class="p">(</code><code class="n">word</code><code class="p">)</code><code class="p">)</code><code> </code><strong><code class="ow">is</code><code> </code><code class="ow">not</code><code> </code><code class="kc">None</code></strong><code class="p">:</code><code>
</code><strong><code>           </code></strong><code> </code><code class="n">exceptions</code><code class="o">.</code><code class="n">append</code><code class="p">(</code><code class="n">InvalidWordError</code><code class="p">(</code><code class="n">word</code><code class="p">,</code><code> </code><code class="n">suggestion</code><code class="p">)</code><code class="p">)</code><code>
</code><strong><code>        </code><code class="k">elif</code></strong><code> </code><code class="p">(</code><code class="n">suggestion</code><code> </code><code class="o">:=</code><code> </code><code class="n">misspelled_words</code><code class="o">.</code><code class="n">get</code><code class="p">(</code><code class="n">word</code><code class="p">)</code><code class="p">)</code><code> </code><strong><code class="ow">is</code><code> </code><code class="ow">not</code><code> </code><code class="kc">None</code><code class="p">:</code></strong><code>
</code><strong><code>           </code></strong><code> </code><code class="n">exceptions</code><code class="o">.</code><code class="n">append</code><code class="p">(</code><code class="n">MisspelledWordError</code><code class="p">(</code><code class="n">word</code><code class="p">,</code><code> </code><code class="n">suggestion</code><code class="p">)</code><code class="p">)</code><code>
</code><strong><code>    </code><code class="k">if</code></strong><code> </code><code class="n">exceptions</code><code class="p">:</code><code>
</code><strong><code>        </code><code class="k">raise</code></strong><code> </code><code class="n">ExceptionGroup</code><code class="p">(</code><code class="s1">'</code><code class="s1">Found grammar errors</code><code class="s1">'</code><code class="p">,</code><code> </code><code class="n">exceptions</code><code class="p">)</code></pre>
<p>The following code validates a sample text string and lists out all the found errors:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">text</code><code> </code><code class="o">=</code><code> </code><code class="s2">"</code><code class="s2">Irregardless a hot dog ain</code><code class="s2">'</code><code class="s2">t a tacco</code><code class="s2">"</code><code>
</code><strong><code class="k">try</code></strong><strong><code class="p">:</code></strong><code>
</code><strong><code>   </code></strong><code> </code><code class="n">check_grammar</code><code class="p">(</code><code class="n">text</code><code class="p">)</code><code>
</code><code class="k">except</code><code class="o">*</code><code> </code><code class="n">InvalidWordError</code><code> </code><strong><code class="k">as</code></strong><code> </code><code class="n">iwe</code><strong><code class="p">:</code></strong><code>
</code><strong><code>   </code></strong><code> </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="se">\n</code><code class="s1">'</code><code class="o">.</code><code class="n">join</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="si">{</code><code class="n">e</code><code class="o">.</code><code class="n">found</code><code class="si">!r}</code><code class="s1"> is not a word, use </code><code class="si">{</code><code class="n">e</code><code class="o">.</code><code class="n">suggestion</code><code class="si">!r}</code><code class="s1">'</code><code>
</code><strong><code>                    </code><code class="k">for</code></strong><code> </code><code class="n">e</code><code> </code><strong><code class="ow">in</code></strong><code> </code><code class="n">iwe</code><strong><code class="o">.</code></strong><code class="n">exceptions</code><code class="p">)</code><code class="p">)</code><code>
</code><code class="k">except</code><code class="o">*</code><code> </code><code class="n">MisspelledWordError</code><code> </code><strong><code class="k">as</code></strong><code> </code><code class="n">mwe</code><code class="p">:</code><code>
</code><strong><code>  </code></strong><code>  </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="se">\n</code><code class="s1">'</code><code class="o">.</code><code class="n">join</code><code class="p">(</code><code class="sa">f</code><code class="s1">'</code><code class="s1">Found </code><code class="si">{</code><code class="n">e</code><code class="o">.</code><code class="n">found</code><code class="si">!r}</code><code class="s1">, perhaps you meant</code><code class="s1">'</code><code>
</code><code>                    </code><code class="sa">f</code><code class="s1">'</code><code class="s1"> </code><code class="si">{</code><code class="n">e</code><code class="o">.</code><code class="n">suggestion</code><code class="si">!r}</code><code class="s1">?</code><code class="s1">'</code><code>
</code><strong><code>                    </code><code class="k">for</code></strong><code> </code><code class="n">e</code><code> </code><strong><code class="ow">in</code></strong><code> </code><code class="n">mwe</code><strong><code class="o">.</code></strong><code class="n">exceptions</code><code class="p">)</code><code class="p">)</code><code>
</code><strong><code class="k">else</code></strong><strong><code class="p">:</code></strong><code>
</code><strong><code>  </code></strong><code>  </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">No errors!</code><code class="s1">'</code><code class="p">)</code></pre>
<p>giving this output:</p>
<pre data-type="programlisting">
<strong>'irregardless' is not a word, use 'regardless'</strong>
<strong>"ain't" is not a word, use "isn't"</strong>
<strong>Found 'tacco', perhaps you meant 'taco'?</strong></pre>
<p>Unlike <span class="code"><strong>except</strong></span>, after it finds an initial match, <span class="code"><strong>except*</strong></span> continues to look for additional exception handlers matching exception types in the raised <span class="code">ExceptionGroup</span>.<a contenteditable="false" data-primary="" data-startref="EXgrpstar06" data-type="indexterm" id="idm44924568573760"/></p>
</div></section>
<section data-pdf-bookmark="Error-Checking Strategies" data-type="sect1"><div class="sect1" id="error_checking_strategies">
<h1>Error-Checking Strategies</h1>
<p>Most<a contenteditable="false" data-primary="exceptions" data-secondary="error-checking strategies" data-type="indexterm" id="EXerchk06"/> programming languages that support exceptions raise exceptions only in rare cases. Python’s emphasis is different. Python deems exceptions appropriate whenever they make a program simpler and more robust, even if that makes exceptions rather frequent.</p>
<section data-pdf-bookmark="LBYL Versus EAFP" data-type="sect2"><div class="sect2" id="lbyl_versus_eafp">
<h2>LBYL Versus EAFP</h2>
<p>A<a contenteditable="false" data-primary="error-checking strategies" data-secondary="look before you leap (LBYL)" data-type="indexterm" id="idm44924568522432"/><a contenteditable="false" data-primary="look before you leap (LBYL)" data-type="indexterm" id="idm44924568521088"/><a contenteditable="false" data-primary="LBYL (look before you leap)" data-type="indexterm" id="idm44924568520016"/> common idiom in other languages, sometimes known as “look before you leap” (LBYL), is to check in advance, before attempting an operation, for anything that might make the operation invalid. This approach is not ideal, for several reasons:</p>
<ul>
<li>
<p>The checks may diminish the readability and clarity of the common, mainstream cases where everything is OK.</p>
</li>
<li>
<p>The work needed for checking purposes may duplicate a substantial part of the work done in the operation itself.</p>
</li>
<li>
<p>The programmer might easily err by omitting a needed check.</p>
</li>
<li>
<p>The situation might change between the moment when you perform the checks and the moment when, later (even by a tiny fraction of a second!), you attempt the operation.</p>
</li>
</ul>
<p>The<a contenteditable="false" data-primary="It’s easier to ask forgiveness than permission (EAFP)" data-type="indexterm" id="idm44924568514240"/><a contenteditable="false" data-primary="EAFP (It’s easier to ask forgiveness than permission)" data-type="indexterm" id="idm44924568513136"/> preferred idiom in Python is to attempt the operation in a <span class="code"><strong>try</strong></span> clause and handle the exceptions that may result in one or more <span class="code"><strong>except</strong></span> clauses. This idiom is known as <a href="https://oreil.ly/rGXC9">“It’s easier to ask forgiveness than permission” (EAFP)</a>, a frequently quoted motto widely credited to Rear Admiral Grace Murray Hopper, co-inventor of COBOL. EAFP shares none of the defects of LBYL. Here is a function using the LBYL idiom:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">safe_divide_1</code><code class="p">(</code><code class="n">x</code><code class="p">,</code><code> </code><code class="n">y</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">if</code></strong><code> </code><code class="n">y</code><code class="o">==</code><code class="mi">0</code><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">Divide-by-0 attempt detected</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code>        </code><code class="k">return</code><code> </code><code class="kc">None</code></strong><code>
</code><code>    </code><strong><code class="k">else</code></strong><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="n">x</code><code class="o">/</code><code class="n">y</code></pre>
<p>With LBYL, the checks come first, and the mainstream case is somewhat hidden at the end of the function.</p>
<p class="pagebreak-before">Here is the equivalent function using the EAFP idiom:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">safe_divide_2</code><code class="p">(</code><code class="n">x</code><code class="p">,</code><code> </code><code class="n">y</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="n">x</code><code class="o">/</code><code class="n">y</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="ne">ZeroDivisionError</code><code class="p">:</code><code>
</code><code>        </code><code class="nb">print</code><code class="p">(</code><code class="s1">'</code><code class="s1">Divide-by-0 attempt detected</code><code class="s1">'</code><code class="p">)</code><code>
</code><strong><code>        </code><code class="k">return</code><code> </code><code class="kc">None</code></strong></pre>
<p>With EAFP, the mainstream case is up front in a <span class="code"><strong>try</strong></span> clause, and the anomalies are handled in the following <span class="code"><strong>except</strong></span> clause, making the whole function easier to read and understand.</p>
<p>EAFP is a good error-handling strategy, but it is not a panacea. In particular, you must take care not to cast too wide a net, catching errors that you did not expect and therefore did not mean to catch. The following is a typical case of such a risk (we cover built-in function <span class="code">getattr</span> in <a data-type="xref" href="ch08.xhtml#pythonapostrophes_core_built_in_functio">Table 8-2</a>):</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">trycalling</code><code class="p">(</code><code class="n">obj</code><code class="p">,</code><code> </code><code class="n">attrib</code><code class="p">,</code><code> </code><code class="n">default</code><code class="p">,</code><code> </code><code class="o">*</code><code class="n">args</code><code class="p">,</code><code> </code><code class="o">*</code><code class="o">*</code><code class="n">kwds</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="nb">getattr</code><code class="p">(</code><code class="n">obj</code><code class="p">,</code><code> </code><code class="n">attrib</code><code class="p">)</code><code class="p">(</code><code class="o">*</code><code class="n">args</code><code class="p">,</code><code> </code><code class="o">*</code><code class="o">*</code><code class="n">kwds</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="ne">AttributeError</code><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="n">default</code></pre>
<p>The intention of the <span class="code">trycalling</span> function is to try calling a method named <span class="code"><em>attrib</em></span> on the object <span class="code"><em>obj</em></span>, but to return <span class="code"><em>default</em></span> if <span class="code"><em>obj</em></span> has no method thus named. However, the function as coded does not do <em>just</em> that: it also accidentally hides any error case where an <span class="code">AttributeError</span> is raised inside the sought-after method, silently returning <span class="code"><em>default</em></span> in those cases. This could easily hide bugs in other code. To do exactly what’s intended, the function must take a little bit more care:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">def</code></strong><code> </code><code class="nf">trycalling</code><code class="p">(</code><code class="n">obj</code><code class="p">,</code><code> </code><code class="n">attrib</code><code class="p">,</code><code> </code><code class="n">default</code><code class="p">,</code><code> </code><code class="o">*</code><code class="n">args</code><code class="p">,</code><code> </code><code class="o">*</code><code class="o">*</code><code class="n">kwds</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><strong><code class="k">try</code></strong><code class="p">:</code><code>
</code><code>        </code><code class="n">method</code><code> </code><code class="o">=</code><code> </code><code class="nb">getattr</code><code class="p">(</code><code class="n">obj</code><code class="p">,</code><code> </code><code class="n">attrib</code><code class="p">)</code><code>
</code><code>    </code><strong><code class="k">except</code></strong><code> </code><code class="ne">AttributeError</code><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="n">default</code><code>
</code><code>    </code><strong><code class="k">else</code></strong><code class="p">:</code><code>
</code><code>        </code><strong><code class="k">return</code></strong><code> </code><code class="n">method</code><code class="p">(</code><code class="o">*</code><code class="n">args</code><code class="p">,</code><code> </code><code class="o">*</code><code class="o">*</code><code class="n">kwds</code><code class="p">)</code></pre>
<p>This implementation of <span class="code">trycalling</span> separates the <span class="code">getattr</span> call, placed in the <span class="code"><strong>try</strong></span> clause and therefore guarded by the handler in the <span class="code"><strong>except</strong></span> clause, from the call of the method, placed in the <span class="code"><strong>else</strong></span> clause and therefore free to propagate any exception. The proper approach to EAFP involves frequent use of the <span class="code"><strong>else</strong></span> clause in <span class="keep-together"><span class="code"><strong>try</strong></span><span class="code">/<strong>except</strong></span></span> statements (which is more explicit, and thus better Python style, than just placing the nonguarded code after the whole <span class="code"><strong>try</strong>/</span><span class="code"><strong>except</strong></span> statement).</p>
</div></section>
<section data-pdf-bookmark="Handling Errors in Large Programs" data-type="sect2"><div class="sect2" id="handling_errors_in_large_programs">
<h2>Handling Errors in Large Programs</h2>
<p>In<a contenteditable="false" data-primary="error-checking strategies" data-secondary="handling errors in large programs" data-type="indexterm" id="idm44924568218560"/> large programs, it is especially easy to err by making your <span class="code"><strong>try</strong></span><span class="code">/<strong>except</strong></span> statements too broad, particularly once you have convinced yourself of the power of EAFP as a general error-checking strategy. A <span class="code"><strong>try</strong>/</span><span class="code"><strong>except</strong></span> combination is too broad when it catches too many different errors, or an error that can occur in too many different places. The latter is a problem when you need to distinguish exactly what went wrong and where, and the information in the traceback is not sufficient to pinpoint such details (or you discard some or all of the information in the traceback). For effective error handling, you have to keep a clear distinction between errors and anomalies that you expect (and thus know how to handle) and unexpected errors and anomalies that may indicate a bug in your program.</p>
<p>Some errors and anomalies are not really erroneous, and perhaps not even all that anomalous: they are just special “edge” cases, perhaps somewhat rare but nevertheless quite expected, which you choose to handle via EAFP rather than via LBYL to avoid LBYL’s many intrinsic defects. In such cases, you should just handle the anomaly, often without even logging or reporting it.</p>
<div data-type="warning" epub:type="warning">
<h1>Keep Your try/except Constructs Narrow</h1>
<p>Be very careful to keep <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>except</strong></span> constructs as narrow as feasible. Use a small <span class="code"><strong>try</strong></span> clause that contains a small amount of code that doesn’t call too many other functions, and use very specific exception class tuples in the <span class="code"><strong>except</strong></span> clauses. If need be, further analyze the details of the exception in your handler code, and <span class="code"><strong>raise</strong></span> again as soon as you know it’s not a case this handler can deal with.</p>
</div>
<p>Errors and anomalies that depend on user input or other external conditions not under your control are always expected, precisely because you have no control over their underlying causes. In such cases, you should concentrate your effort on handling the anomaly gracefully, reporting and logging its exact nature and details, and keeping your program running with undamaged internal and persistent state. Your <span class="code"><strong>try</strong></span><span class="code">/</span><span class="code"><strong>except</strong></span> clauses should still be reasonably narrow, although this is not quite as crucial as when you use EAFP to structure your handling of not-really-erroneous special/edge cases.</p>
<p>Lastly, entirely unexpected errors and anomalies indicate bugs in your program’s design or coding. In most cases, the best strategy regarding such errors is to avoid <span class="code"><strong>try</strong></span><span class="code">/<strong>except</strong></span> and just let the program terminate with error and traceback messages. (You might want to log such information and/or display it more suitably with an application-specific hook in <span class="code">sys.excepthook</span>, as we’ll discuss shortly.) In the unlikely case that your program must keep running at all costs, even under dire circumstances, <span class="code"><strong>try</strong>/</span><span class="code"><strong>except</strong></span> statements that are quite wide may be appropriate, with the <span class="code"><strong>try</strong></span> clause guarding function calls that exercise vast swaths of program functionality, and broad <span class="code"><strong>except</strong></span> clauses.</p>
<p>In the case of a long-running program, make sure to log all details of the anomaly or error to some persistent place for later study (and also report to yourself some indication of the problem, so that you know such later study is necessary). The key is making sure that you can revert the program’s persistent state to some undamaged, internally consistent point. The techniques that enable long-running programs to survive some of their own bugs, as well as environmental adversities, are known as<a contenteditable="false" data-primary="checkpointing" data-type="indexterm" id="idm44924568197712"/> <a href="https://oreil.ly/GX4hz">checkpointing</a> (basically, periodically saving program state, and writing the program so it can reload the saved state and continue from there) and<a contenteditable="false" data-primary="transaction processing" data-type="indexterm" id="idm44924568195760"/> <a href="https://oreil.ly/0MaWS">transaction processing</a>; we do not cover them further in this book.</p>
</div></section>
<section data-pdf-bookmark="Logging Errors" data-type="sect2"><div class="sect2" id="logging_errors">
<h2>Logging Errors</h2>
<p>When<a contenteditable="false" data-primary="error-checking strategies" data-secondary="logging errors" data-type="indexterm" id="ECSlog06"/><a contenteditable="false" data-primary="logging" data-secondary="errors" data-type="indexterm" id="Lerror06"/> Python propagates an exception all the way to the top of the stack without finding an applicable handler, the interpreter normally prints an error traceback to the standard error stream of the process (<span class="code">sys.stderr</span>) before terminating the program. You can rebind <span class="code">sys.stderr</span> to any file-like object usable for output in order to divert this information to a destination more suitable for your purposes.</p>
<p>When you want to change the amount and kind of information output on such occasions, rebinding <span class="code">sys.stderr</span> is not sufficient. In such cases, you can assign your own function to <span class="code">sys.excepthook</span>: Python calls it when terminating the program due to an unhandled exception. In your exception-reporting function, output whatever information will help you diagnose and debug the problem and direct that information to whatever destinations you please. For example, you might use the <span class="code">traceback</span> module (covered in <a data-type="xref" href="ch17.xhtml#the_traceback_module">“The traceback Module”</a>) to format stack traces. When your exception-reporting function terminates, so does your program.</p>
<section data-pdf-bookmark="The logging module" data-type="sect3"><div class="sect3" id="the_logging_module">
<h3>The logging module</h3>
<p>The Python standard library offers the rich and powerful<a contenteditable="false" data-primary="logging" data-secondary="logging module" data-type="indexterm" id="idm44924568180992"/><a contenteditable="false" data-primary="standard library modules" data-secondary="logging" data-type="indexterm" id="idm44924568179616"/> <span class="code">logging</span> module to let you organize the logging of messages from your applications in systematic, flexible ways. Pushing things to the limit, you might write a whole hierarchy of <span class="code">Logger</span> classes and subclasses; you could couple the loggers with instances of <span class="code">Handler</span> (and subclasses thereof), or insert instances of the class <span class="code">Filter</span> to fine-tune criteria determining what messages get logged in which ways.</p>
<p>Messages are formatted by instances of the <span class="code">Formatter</span> class—the messages themselves are instances of the <span class="code">LogRecord</span> class. The <span class="code">logging</span> module even includes a dynamic configuration facility, whereby you may dynamically set logging configuration files by reading them from disk files, or even by receiving them on a dedicated socket in a specialized thread.</p>
<p>While the <span class="code">logging</span> module sports a frighteningly complex and powerful architecture, suitable for implementing highly sophisticated logging strategies and policies that may be needed in vast and complicated software systems, in most applications you might get away with using a tiny subset of the package. First, <span class="code"><strong>import</strong></span> <span class="code">logging</span>. Then, emit your message by passing it as a string to any of the module’s functions <span class="code">debug</span>, <span class="code">info</span>, <span class="code">warning</span>, <span class="code">error</span>, or <span class="code">critical</span>, in increasing order of severity. If<a contenteditable="false" data-primary="% (percent sign)" data-secondary="log message placeholder" data-type="indexterm" id="idm44924568166352"/><a contenteditable="false" data-primary="percent sign (%)" data-secondary="log message placeholder" data-type="indexterm" id="idm44924568164976"/> the string you pass contains format specifiers such as <span class="code">%s</span> (as covered in <a data-type="xref" href="ch09.xhtml#legacy_string_formatting_with_percent">“Legacy String Formatting with %”</a>), then, after the string, pass as further arguments all the values to be formatted in that string. For example, don’t call:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">logging</code><code class="o">.</code><code class="n">debug</code><code class="p">(</code><code class="s1">'foo is </code><code class="si">%r</code><code class="s1">'</code> <code class="o">%</code> <code class="n">foo</code><code class="p">)</code></pre>
<p>which performs the formatting operation whether it’s needed or not; rather, call:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">logging</code><code class="o">.</code><code class="n">debug</code><code class="p">(</code><code class="s1">'foo is </code><code class="si">%r</code><code class="s1">'</code><code class="p">,</code> <code class="n">foo</code><code class="p">)</code></pre>
<p>which performs formatting if and only if needed (i.e., if and only if calling debug is going to result in logging output, depending on the current threshold logging level). If <span class="code">foo</span> is used only for logging and is especially compute- or I/O-intensive to create, you can use <span class="code">isEnabledFor</span> to conditionalize the expensive code that creates <span class="code">foo</span>:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">if</code></strong><code> </code><code class="n">logging</code><code class="o">.</code><code class="n">getLogger</code><code class="p">(</code><code class="p">)</code><code class="o">.</code><code class="n">isEnabledFor</code><code class="p">(</code><code class="n">logging</code><code class="o">.</code><code class="n">DEBUG</code><code class="p">)</code><code class="p">:</code><code>
</code><code>    </code><code class="n">foo</code><code> </code><code class="o">=</code><code> </code><code class="n">cpu_intensive_function</code><code class="p">(</code><code class="p">)</code><code>
</code><code>    </code><code class="n">logging</code><code class="o">.</code><code class="n">debug</code><code class="p">(</code><code class="s1">'</code><code class="s1">foo is </code><code class="si">%r</code><code class="s1">'</code><code class="p">,</code><code> </code><code class="n">foo</code><code class="p">)</code></pre>
</div></section>
<section data-pdf-bookmark="Configuring logging" data-type="sect3"><div class="sect3" id="configuring_logging">
<h3>Configuring logging</h3>
<p>Unfortunately, the <span class="code">logging</span> module does not support the more readable formatting approaches covered in <a data-type="xref" href="ch09.xhtml#string_formatting">“String Formatting”</a>, but only the legacy one mentioned in the previous subsection. Fortunately, it’s very rare to need any formatting specifiers beyond <span class="code">%s</span> (which calls <span class="code">__str__</span>) and <span class="code">%r</span> (which calls <span class="code">__repr__</span>).</p>
<p>By default, the threshold level is <span class="code">WARNING</span>: any of the functions <span class="code">warning</span>, <span class="code">error</span>, or <span class="code">critical</span> results in logging output, but the functions <span class="code">debug</span> and <span class="code">info</span> do not. To change the threshold level at any time, call <span class="code">logging.getLogger().setLevel</span>, passing as the only argument one of the corresponding constants supplied by the <span class="code">logging</span> module: <span class="code">DEBUG</span>, <span class="code">INFO</span>, <span class="code">WARNING</span>, <span class="code">ERROR</span>, or <span class="code">CRITICAL</span>. For example, once you call:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">logging</code><code class="o">.</code><code class="n">getLogger</code><code class="p">()</code><code class="o">.</code><code class="n">setLevel</code><code class="p">(</code><code class="n">logging</code><code class="o">.</code><code class="n">DEBUG</code><code class="p">)</code></pre>
<p>all of the logging functions from <span class="code">debug</span> to <span class="code">critical</span> result in logging output until you change the level again. If later you call:</p>
<pre data-code-language="python" data-type="programlisting">
<code class="n">logging</code><code class="o">.</code><code class="n">getLogger</code><code class="p">()</code><code class="o">.</code><code class="n">setLevel</code><code class="p">(</code><code class="n">logging</code><code class="o">.</code><code class="n">ERROR</code><code class="p">)</code></pre>
<p>then only the functions <span class="code">error</span> and <span class="code">critical</span> result in logging output (<span class="code">debug</span>, <span class="code">info</span>, and <span class="code">warning</span> won’t result in logging output); this condition, too, persists until you change the level again, and so forth.</p>
<p>By default, logging output goes to your process’s standard error stream (<span class="code">sys.stderr</span>, as covered in <a data-type="xref" href="ch08.xhtml#functions_and_attributes_of_the_sys_mod">Table 8-3</a>) and uses a rather simplistic format (for example, it does not include a timestamp on each line it outputs). You can control these settings by instantiating an appropriate handler instance, with a suitable formatter instance, and creating and setting a new logger instance to hold it. In the simple, common case in which you just want to set these logging parameters once and for all, after which they persist throughout the run of your program, the simplest approach is to call the <span class="code">logging.basicConfig</span> function, which lets you set things up quite simply via named parameters. Only the very first call to <span class="code">logging.basicConfig</span> has any effect, and only if you call it before any of the logging functions (<span class="code">debug</span>, <span class="code">info</span>, and so on). Therefore, the most common use is to call <span class="code">logging.basicConfig</span> at the very start of your program. For example, a common idiom at the start of a program is something like:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="kn">import</code></strong><code> </code><code class="nn">logging</code><code>
</code><code class="n">logging</code><code class="o">.</code><code class="n">basicConfig</code><code class="p">(</code><code>
</code><code>    </code><code class="nb">format</code><code class="o">=</code><code class="s1">'</code><code class="si">%(asctime)s</code><code class="s1"> </code><code class="si">%(levelname)8s</code><code class="s1"> </code><code class="si">%(message)s</code><code class="s1">'</code><code class="p">,</code><code>
</code><code>    </code><code class="n">filename</code><code class="o">=</code><code class="s1">'</code><code class="s1">/tmp/logfile.txt</code><code class="s1">'</code><code class="p">,</code><code> </code><code class="n">filemode</code><code class="o">=</code><code class="s1">'</code><code class="s1">w</code><code class="s1">'</code><code class="p">)</code></pre>
<p>This setting writes logging messages to a file, nicely formatted with a precise human-readable timestamp, followed by the severity level right-aligned in an eight-character field, followed by the message proper.</p>
<p>For much, much more detailed information on the <span class="code">logging</span> module and all the wonders you can perform with it, be sure to consult Python’s <a href="https://oreil.ly/AO1Xa">rich online documentation</a><em>.<a contenteditable="false" data-primary="" data-startref="EXerchk06" data-type="indexterm" id="idm44924567916896"/><a contenteditable="false" data-primary="" data-startref="ECSlog06" data-type="indexterm" id="idm44924567915488"/><a contenteditable="false" data-primary="" data-startref="Lerror06" data-type="indexterm" id="idm44924567914112"/></em></p>
</div></section>
</div></section>
</div></section>
<section data-pdf-bookmark="The assert Statement" data-type="sect1"><div class="sect1" id="the_assert_statement">
<h1>The assert Statement</h1>
<p>The<a contenteditable="false" data-primary="exceptions" data-secondary="assert statement" data-type="indexterm" id="idm44924567911104"/><a contenteditable="false" data-primary="assert statement" data-type="indexterm" id="idm44924567886416"/> <span class="code"><strong>assert</strong></span> statement allows you to introduce “sanity checks” into a program. <span class="code"><strong>assert</strong></span> is a simple statement with the following syntax:</p>
<pre data-code-language="python" data-type="programlisting">
<strong><code class="k">assert</code></strong><code> </code><em><code class="n">condition</code></em><code class="p">[</code><code class="p">,</code><code> </code><em><code class="n">expression</code></em><code class="p">]</code></pre>
<p>When you run Python with the optimize flag (<span class="code"><strong>-O</strong></span>, as covered in <a data-type="xref" href="ch02.xhtml#command_line_syntax_and_options">“Command-Line Syntax and Options”</a>), <span class="code"><strong>assert</strong></span> is a null operation: the compiler generates no code for it. Otherwise, <span class="code"><strong>assert</strong></span> evaluates <span class="code"><em>condition</em></span>. When <span class="code"><em>condition</em></span> is satisfied, <span class="code"><strong>assert</strong></span> does nothing. When <span class="code"><em>condition</em></span> is not satisfied, <span class="code"><strong>assert</strong></span> instantiates <span class="code">AssertionError</span> with <span class="code"><em>expression</em></span> as the argument (or without arguments, if there is no <span class="code"><em>expression</em></span>) and raises the resulting instance.<sup><a data-type="noteref" href="ch06.xhtml#ch01fn80" id="ch01fn80-marker">3</a></sup></p>
<p><span class="code"><strong>assert</strong></span> statements can be an effective way to document your program. When you want to state that a significant, nonobvious condition <span class="code"><em>C</em></span> is known to hold at a certain point in a program’s execution (known as an <em>invariant</em> of your program), <span class="code"><strong>assert</strong></span> <span class="code"><em>C</em></span> is often better than a comment that just states that <span class="code"><em>C</em></span> holds.</p>
<div data-type="warning" epub:type="warning">
<h1>Don’t Overuse assert</h1>
<p>Never use <span class="code"><strong>assert</strong></span> for other purposes besides sanity-checking program invariants. A serious but very common mistake is to use <span class="code"><strong>assert</strong></span> about the values of inputs or arguments. Checking for erroneous arguments or inputs is best done more explicitly, and in particular must not be done using <span class="code"><strong>assert</strong></span>, since it can be turned into a null operation by a Python command-line flag.</p>
</div>
<p>The advantage of <span class="code"><strong>assert</strong></span> is that, when <span class="code"><em>C</em></span> does <em>not</em> in fact hold, <span class="code"><strong>assert</strong></span> immediately alerts you to the problem by raising <span class="code">AssertionError</span>, if the program is running without the <span class="code"><strong>-O</strong></span> flag. Once the code is thoroughly debugged, run it with <span class="code"><strong>-O</strong></span>, turning <span class="code"><strong>assert</strong></span> into a null operation and incurring no overhead (the <span class="code"><strong>assert</strong></span> remains in your source code to document the invariant).</p>
<div data-type="tip">
<h1>The __debug__ Built-in Variable</h1>
<p>When<a contenteditable="false" data-primary="__debug__ variable" data-type="indexterm" id="idm44924567824592"/> you run Python without the option <span class="code"><strong>-O</strong></span>, the <span class="code">__debug__</span> built-in variable is <span class="code"><strong>True</strong></span>. When you run Python with the option <span class="code"><strong>-O</strong></span>, <span class="code">__debug__</span> is <span class="code"><strong>False</strong></span>. Also, in the latter case the compiler generates no code for any <span class="code"><strong>if</strong></span> statement whose sole guard condition is <span class="code">__debug__</span>.</p>
<p>To exploit this optimization, surround the definitions of functions that you call only in <span class="code"><strong>assert</strong></span> statements with <span class="code"><strong>if</strong></span> <span class="code">__debug__:</span>. This technique makes compiled code smaller and faster when Python is run with <span class="code"><strong>-O</strong></span>, and enhances program clarity by showing that those functions exist only to perform sanity checks.</p>
</div>
</div></section>
<div data-type="footnotes"><p data-type="footnote" id="ch01fn78"><sup><a href="ch06.xhtml#ch01fn78-marker">1</a></sup> Except that multiple calls to <span class="code">close</span> are allowed and innocuous: all but the first one perform no operation.</p><p data-type="footnote" id="ch01fn79"><sup><a href="ch06.xhtml#ch01fn79-marker">2</a></sup> This is somewhat controversial: while this book’s authors agree on this being “best practice,” some others strongly insist that one should always avoid multiple inheritance, including in this specific case.</p><p data-type="footnote" id="ch01fn80"><sup><a href="ch06.xhtml#ch01fn80-marker">3</a></sup> Some third-party frameworks, such as <a href="http://docs.pytest.org/en/latest"><span class="code">pytest</span></a>, materially improve the usefulness of the <span class="code"><strong>assert</strong></span> statement.</p></div></div></section></div></body></html>